### ISSUE TITLE
What is the status of "Restoring bash history (experimental)"

### ISSUE THREAD

**Issue by foice** [tmux-plugins/tmux-resurrect#100]
I will be happy to play a bit with this feature and see how it works. However the page does not explain much of what it does (and how).
Before getting wet with the test, may I ask what is the status of this experimental feature?
Thanks
Roberto

**Comment by bruno-** [comment]
Hi,
this feature saves and restores exact bash command history for each tmux pane.

For example: if your last command in pane `x` was `git checkout master` and this feature is enabled, after restore, you will be able to press `up` key in the restored pane `x` and `git checkout master` will show up.

In order for it to work, this feature runs an additional command in each pane. This makes it pretty dirty. We never figured out how to remove this. Also, it's a bash-only feature.

If you're curious feel free to try out this feature, but I think you might quickly realize how annoying these extra commands in tmux panes are. Unless someone has a genius idea how to make this work smoothly and for all shells I think we might end up deprecating this feature in the future.

Closing this as it seems it's not an issue, but feel free to continue the discussion.

**Comment by foice** [comment]
Thanks for your kind reply and for the explanation. The feature you
describe seems quite needed indeed.

May I ask what is the dirty command you talk about?

I was investigating how to cook up a recipe for this and, maybe you know
this already.  I saw this post reply by waltinator
<http://askubuntu.com/users/25618/waltinator> where history files are
associated to the bash PID. As far as I can see in each windows/pane my
bash has a different PID, so it might work to track the different
histories.
http://askubuntu.com/questions/80371/bash-history-handling-with-multiple-terminals

Also there is this
https://github.com/markeissler/tmux-resurrect-ng
maybe based on the same dirty trick you will eventually deprecate?
