### ISSUE TITLE
Option to kill 0 session

### ISSUE THREAD

**Issue by ain** [tmux-plugins/tmux-resurrect#101]
**Use-case**: 
1. Restarting a machine
2. `tmux`
3. Restore

**What happens**: sessions restored, but there's a 0 session, the 1st one that launched in step 2.

**What could happen**: with some smart configuration flag, that 0 session could be killed during the restore, it's clutter.

**Comment by nesl247** [comment]
Ah, so it wasn't just something odd that I was doing. I thought I had done something wrong.

**Comment by ain** [comment]
I'd change this feature idea also to incorporate a command line tool, e.g. tmux-resurrect that would start tmux, restore and explicitly kill the 0 session once done.

**Comment by paulhybryant** [comment]
hi, I have the same issue and this is what I use to achieve what you need here:

In .tmux.conf, add the following line in the end
if-shell '[[ $(tmux list-sessions | wc -l ) -eq 0 ]]' 'run-shell $HOME/.tmux/plugins/tmux-resurrect/scripts/restore.sh'

create an alias, e.g. alias tmux-start='tmux start-server; tmux attach'
Then when use tmux-start and no dummy session will be created, with all your saved sessions resurrected.

**Comment by ain** [comment]
I think it's a good direction, but it's failing in the scenario which does not have any sessions so `tmux attach` would simply throw `no sessions`.

**Comment by paulhybryant** [comment]
Yeah, you should only use the alias tmux-start when you saved your session.
Otherwise just use tmux as usual.

**Comment by soyuka** [comment]
After restoring it could:

```bash
//go to second session if first is 0 
tmux attach-session -t $(tmux list-session | head -n 1 | awk '{print $1}')
//delete first one
tmux kill-session -t 0
```

**Comment by paulhybryant** [comment]
In my case it is slightly different. The session created after restoring is
not "0", but "4" (because I have three saved sessions).
So relying on killing the session with name "0" is a bit unreliable.

On Sat, Dec 12, 2015 at 3:41 AM, Antoine Bluchet <notifications@github.com>
wrote:

> After restoring it could:
>
> //go to second session if first is 0
> tmux attach-session -t $(tmux list-session | head -n 1 | awk '{print $1}')
> //delete first one
> tmux kill-session -t 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmux-plugins/tmux-resurrect/issues/101#issuecomment-164030890>
> .
>



-- 
With Regards,

Yu Huang

Software Engineer,
Google Inc.

**Comment by unhammer** [comment]
Is there not a way to start tmux and at the same time send in a command to be run?

**Comment by paulhybryant** [comment]
IIUC, what you want can be done by including the command you want to run
when server is being started in .tmux.conf

On Wed, Jan 20, 2016 at 12:00 AM, Kevin Brubeck Unhammer <
notifications@github.com> wrote:

> Is there not a way to start tmux and at the same time send in a command to
> be run?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmux-plugins/tmux-resurrect/issues/101#issuecomment-173122816>
> .
>



-- 
With Regards,

Yu Huang

Software Engineer,
Google Inc.

**Comment by janzenz** [comment]
Whew! I've been banging my head with this and thought I was the only one having this issue. The problem with `tmux start-server` solution is that as of tmux 2.3 this command doesn't run the server by default unless there's a session running. See this [issue](https://github.com/tmux/tmux/issues/182)

**Comment by cedricpim** [comment]
Any solutions to this, for tmux 2.2?

**Comment by Dam0cles** [comment]
If you're using tmux-resurrect, you can just edit the plugin yourself to do so. In `.tmux/plugins/tmux-resurrect/scripts/restore.sh` insert a `tmux kill-session` at the end of the main() function after the restoration being completed, like so:
```
		display_message "Tmux restore complete!"
		tmux kill-session
	fi
}
main
```

**Comment by kaykayehnn** [comment]
Since hooks were added in #267 a simple solution for this is adding `set -g @resurrect-hook-pre-restore-pane-processes 'tmux switch-client -n && tmux kill-session -t=0'` to tmux.conf.

Just keep in mind that session 0 will be killed even if it was one of the restored sessions. This shouldn't be a problem if you name your sessions.

**Comment by rollf** [comment]
I have ``tmux-continuum`` installed and launch tmux by ``tmux a``. This does not create an "empty" session.

**Comment by andersonlzcosta** [comment]
> Since hooks were added in #267 a simple solution for this is adding `set -g @resurrect-hook-pre-restore-pane-processes 'tmux switch-client -n && tmux kill-session -t=0'` to tmux.conf.
> 
> Just keep in mind that session 0 will be killed even if it was one of the restored sessions. This shouldn't be a problem if you name your sessions.

This didn't work for me! I realized that for me it was pretty consistent that was the first session, so I went straight to the point:

`run-shell ~/clone/path/continuum.tmux`

**Comment by bruno-** [comment]
Resurrect will now kill session 0 if that session wasn't on a list of restored sessions.
This is a destructive action and I have long refrained from it.

Please open another issue if you have any problems with this.
