### ISSUE TITLE
Old resurrect-files are not deleted

### ISSUE THREAD

**Issue by nielsk** [tmux-plugins/tmux-resurrect#102]
Old resurrect-files are not deleted, I have tons of them (from today and yesterday 123 files alone). It's only ca 9MB in files after a month of use but still.
Maybe do a resurrect and after that delete all files that are related to the resurrect.

**Comment by bruno-** [comment]
Hey,
this is a known thing. It was never viewed as a problem because file usage is so low.

I sometimes use old save files from a few days back so I don't think `rm *` is the best approach. Maybe we should delete backup files older than 30 days?

Unless someone disagrees let's treat this as a non-high priority thing. I'll leave the issue open so others can comment as well.

**Comment by nielsk** [comment]
30 days sounds good imho (and I also do not think that it is a high-prio-thing but I couldn't find anything in the issue-list and with time even the small files can accumulate to larger space takers.)

**Comment by adoyle-h** [comment]
I think it is necessary to remove these redundant files automatically. Even though it is small, these files should not take up the disk space unlimited over time.(I often forget to check its space occupancy)

I recommend setting some options in tmux.conf to limit the files based on time and space.

**Comment by nikisix** [comment]
Totally agree with adoyle-h

**Comment by soyuka** [comment]
I don't agree it's necessary, I don't save my sessions much and I'd want to keep them. I must've ~3-4 sessions files (if I type ctrl+s by inadvertence, I usually resurrect my correct state and delete it manually),

Btw, as @nikisix  pointed out, it's really easy to do in a cron:

```
# Every month remove resurrect files except the 5 most recent ones
0 0 1 * * ls -tr $HOME/.tmux/resurrect/*.txt | head -n-5 | xargs --no-run-if-empty rm
```

**Comment by bruno-** [comment]
Hi peeps, [this PR is now merged](https://github.com/tmux-plugins/tmux-resurrect/pull/151).

It deletes resurrect files older than 30 days. The minimum number of kept files is 5 (no matter the file age).

**Comment by flajann2** [comment]
I have so many of these resurrect files when I try to delete them, I get an "Argument list too long" error. They go back years. I'll have to write a script to delete them, or just delete the directory itself.

**Comment by nielsk** [comment]
@flajann2 
use find to delete them like 
find . -type f -exec rm {} \;
(That would delete all files in the current directory and sub-directories, so limit it down with something like -name)

**Comment by flajann2** [comment]
@nielsk Thanks.
