### ISSUE TITLE
vim-startify session restore

### ISSUE THREAD

**Issue by francozappa** [tmux-plugins/tmux-resurrect#107]
Hi,

I have troubles restoring my vim sessions using https://github.com/mhinz/vim-startify

It seems that tmux-resurrect records only the `vim` command.without recording the session file.

**Comment by bruno-** [comment]
Hey,
this plugin supports restoring just vanilla vim sessions (with `vim -S`) if `Sesssion.vim` file exists in the directory where vim is started. This is what is described as "The old way" in `vim-startify` readme.

The "strategy" is a simple script and you can check it out [here](https://github.com/tmux-plugins/tmux-resurrect/blob/bd095e739d3706ce98f074b776ff80efbb0493f4/strategies/vim_session.sh#L21-L30).

From what I see `vim-startify` stores sessions files in `~/.vim/session`? If so, this won't work.

I'm not familiar with `vim-startify`, but I think you could get what you want with something this:

    set -g @resurrect-processes 'foo bar "vim->vim -c SLoad"'

**Comment by francozappa** [comment]
Hi Bruno,

I don't understand the `'foo bar'` part of the command. 
Is it a way to hardcode the session names? If it is, It won't solve my problem because I'm using different vim sessions in different windows and sometimes in different tmux sessions.

Thank you !

**Comment by bruno-** [comment]
Hey @francozappa,
`'foo bar'` is just a boilerplate. I don't know why I put it there. `"vim->vim -c SLoad"` is hopefully a valuable piece of info.

More info on `@resurrect-processes` option can be found in [this doc](https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_programs.md).

**Comment by steadystatic** [comment]
@francozappa I'm a vim-startify user, too. One thought is enabling the option `let g:startify_session_autoload = 1` it has the same behavior as the Session.vim files where it loads one up if you start vim from that directory and the file is present. 

There's also `let g:startify_session_persistence = 1` so sessions are saved on events like quitting or loading a new session. That seems helpful.

I'm not working yet but I'm currently using these settings and trying to write a simple vim autocmd using VimLeave to maybe symlink the Session.vim into the corresponding directory and have it work as resurrect expects.

**Comment by mhinz** [comment]
The latest commit makes `:SLoad`, without any argument, load the last used session on Unix.

```vim
" vimrc
let g:startify_session_persistence = 1
```
*+*
```tmux
# tmux.conf
set -g @resurrect-processes '"vim->vim +SLoad"'
```
*=* :heart_eyes:

**Comment by francozappa** [comment]
Thank you @mhinz, this is a killer feature !

**Comment by steadystatic** [comment]
This is so great! Happy vimmer, happy tmuxer :)

**Comment by bruno-** [comment]
:+1:
