### ISSUE TITLE
is tmux-resurrect tested with tmux 2.1?

### ISSUE THREAD

**Issue by foice** [tmux-plugins/tmux-resurrect#114]
just to make sure, "or higher" includes v2.1 releases one week ago.

anyways, if I want to update to 2.1, what is a safe way to backup all my configuration of tmux and this plug-in? if I save the whole .tmux fodler I think is going to work, any better idea or comments?

**Comment by foice** [comment]
seem it does! great

**Comment by bruno-** [comment]
Hi,
yea, I've been running tmux 2.1 for a while now and it's been working ok.

- as for the upgrade process, there's nothing to do: just install new tmux version and things should work.
- regarding the backup: you can save just the `~/.tmux/resurrect/` dir, it's where resurrect files are stored.

It seems thing work on your end too. I'm gonna close the issue, but do let me know if you need more help.
