### ISSUE TITLE
DBUS_SESSION_BUS_ADDRESS is stale on restore

### ISSUE THREAD

**Issue by raghavendra-talur** [tmux-plugins/tmux-resurrect#118]
Thanks for such an awesome tool.

I found that on a restart of system and performing a tmux restore, any commands that rely on finding DBUS_SESSION_BUS_ADDRESS will not work as they find old session path. 

Output from a tmux session
$ echo $DBUS_SESSION_BUS_ADDRESS
unix:abstract=/tmp/dbus-ABi3sKh9P8,guid=94be2813a0f13fd5382412c25644c8f7

Output from a non tmux session
$ echo $DBUS_SESSION_BUS_ADDRESS
unix:abstract=/tmp/dbus-E4chVF3cEj,guid=a80c4604863de795796fe7795645a46d

Note that the paths are different. If you feel that this is not a issue, we can still use this as a tracker for possible workarounds.

**Comment by bruno-** [comment]
Hey,
do you think this is related to this plugin (`tmux-resurrect`) or `tmux` in general?

**Comment by bruno-** [comment]
Any updates on this? I think this issue is not related to tmux-resurrect at all.

**Comment by bruno-** [comment]
Closing as I'm pretty sure this is not related to `tmux-resurrect`
