### ISSUE TITLE
errors in save.sh and restore.sh

### ISSUE THREAD

**Issue by tessus** [tmux-plugins/tmux-resurrect#124]
You are using a single `=` which is an assignment and not a comparison operator.

restore.sh https://github.com/tmux-plugins/tmux-resurrect/blob/master/scripts/restore.sh#L277
should be:
`if [ "$pane_command" == "bash" ]; then`

save.sh https://github.com/tmux-plugins/tmux-resurrect/blob/master/scripts/save.sh#L149
should be:
`if [ "$pane_command" == "bash" ] && [ "$full_command" == ":" ]; then`

**Comment by bruno-** [comment]
> You are using a single = which is an assignment and not a comparison operator

Are you sure? http://stackoverflow.com/questions/3265803/bash-string-equality

**Comment by tessus** [comment]
>  Are you sure? http://stackoverflow.com/questions/3265803/bash-string-equality

I was until now. I must have mixed it up with another shell/script/language.
