### ISSUE TITLE
Detaches all processes

### ISSUE THREAD

**Issue by zoqaeski** [tmux-plugins/tmux-resurrect#142]
Saving a session after a reload causes all processes that were saved to be restarted but detached so I can't use them anymore. If I use the `capture-pane-contents` option then I get the contents of the pane, but the running applications are inaccessible. The `resurrect-processes` option is supposed to restart nvim, htop, and ranger.

tmux plugins:

```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'

# Resurrect settings
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'nvim htop ranger'
```

**Comment by bruno-** [comment]
Hey, we've had an issue where some processes were not restored. This should now be fixed. Can you please try pulling the latest plugin version and seeing if things are now ok?
