### ISSUE TITLE
current working directory not restored when .bashrc contains cd somepath

### ISSUE THREAD

**Issue by michalre** [tmux-plugins/tmux-resurrect#143]
I am having a problem with current working directory restoration. I have cd somepath in my .bashrc file and it seems to execute after tmux-resurrect restores the current working directory.
Is there any way how to make it work?

**Comment by bruno-** [comment]
Hey,
it seems bash shell initialization comes **after** tmux creates a pane with a given dir. Forcing the pane directory beyond pane initialization is not supported.
