### ISSUE TITLE
fail with vim-session

### ISSUE THREAD

**Issue by jacoborus** [tmux-plugins/tmux-resurrect#145]
I'm using [xolox/vim-session](https://github.com/xolox/vim-session) for session management on neovim, does this stack work with tmux-resurrect?
I added `set -g @resurrect-strategy-nvim 'session'` to my .tmux.conf but I am getting just the last printed view of neovim instead a real nvim instance
I'm using tmux 2.3 and neovim 0.1.5-dev

**Comment by ChrisCPO** [comment]
I'm having a similar issue with normal vim. added the line to my tmux.conf file and I do use the tpope/vim-obsession gem. Where is this Sessions.vim file supposed to live?

**Comment by maurizzzio** [comment]
@jacoborus vim-session saves a named session inside `g:session_directory` which you can use to restore the session e.g. a session named example `example` might be restored as

```sh
nvim -S ~/.config/nvim/session/example.vim
```

The downside of this approach is that you need to have a named session for each project which in the long run became tedious, I switched to tpope/vim-obsession instead

@ChrisCPO The session file can live anywhere provided that you start vim/nvim with the correct path to it (defaults to `./Session.vim`), I have the following workflow for new projects

- Start vim from your project root
- Start recording a session with `:Obsession`, this will create a `Session.vim` in the path vim/neovim was invoked from
- Exit vim
- Start vim again with `vim -S`
- Take a snapshot of your current tmux sessions with `prefix + <C-s>`

Also make sure that you have this line on your `.tmux.conf` file

```sh
set -g @resurrect-strategy-vim 'session'
```

**Comment by jacoborus** [comment]
I already have a named session for each project, so I write a script that opens all tmux sessions and also neovim ones. I'm closing this issue ( @ChrisCPO let me know if you still have the problem and I will reopen it)

**Comment by ChrisCPO** [comment]
@jacoborus  nope I'm good thanks for the help

**Comment by jacoborus** [comment]
thanks @maurizzzio !
