### ISSUE TITLE
Restoring... animation persists forever

### ISSUE THREAD

**Issue by Insanityandme** [tmux-plugins/tmux-resurrect#153]
So this is what it looks like:
![screen shot 2016-07-11 at 12 10 00](https://cloud.githubusercontent.com/assets/1380257/16727232/6c906e50-4760-11e6-804a-5fe6e1abe120.png)

I've tried reinstalling tmux, I've even deleted the plugins tmux-resurrect and tmux-continuum and removed any configs related to them and it still persists.

Here's my tmux.conf config:
`for debugging scripts
set -x

Colorscheme/Look of TMUX 
Improve Colors
set -g default-terminal "screen-256color"

Statusbar colors
set -g status-fg "#AFAF68"
set -g status-bg default

Statusbar settings
set -g status-justify left
setw -g window-status-format "#I: #W"
setw -g window-status-current-format "[#I: #W]"

set -g status-left ''
set -g status-right '[%Y-%D  %H:%M]'

Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

Bindings
Ctrl-a instead of Ctrl-b (acting like GNU screen)
unbind C-b
set -g prefix C-a

Vi mode, Switch panes with HJKL
set-window-option -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

Window splits
bind - split-window -h
bind _ split-window -v

Last pane
bind-key C-a last-pane

Reload config file 
bind r source-file ~/.tmux.conf

Start window index at 1, renumber windows after closing
set -g base-index 1

List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

Automatic tmux start + automatic restore
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'full-screen'
set -g @continuum-restore 'on'

Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

run-shell '~/.tmux/plugins/tmux-resurrect/resurrect.tmux'
`

So I commented out the last 8 lines, in other words the plugins and the settings for them to work but to no avail. 

This is my first time making a post so please tell me if you want me to add more information. 

Thanks.

**Comment by Insanityandme** [comment]
Sorry, It's been taken care of now.

**Comment by wongjustin99** [comment]
If anyone runs into this, make sure to do a `ps aux | grep tmux` and check for other shells running tmux.
