### ISSUE TITLE
Save configuration only if it was changed (patch included)

### ISSUE THREAD

**Issue by vburdo** [tmux-plugins/tmux-resurrect#156]
Hi

Thanks for great plugin.
I'm using Resurrect with Continuum and it produces enormous number of identical saves, even if terminal is inactive.
I fixed it by comparing current save with last save. And, if they are identical, I just dump current save.

I don't think I need pull request for this small fix.
So, here is the patch:

---

diff --git a/scripts/save.sh b/scripts/save.sh
index 137e229..d36674a 100755
--- a/scripts/save.sh
+++ b/scripts/save.sh
@@ -259,7 +259,11 @@ save_all() {
    dump_panes   >> "$resurrect_file_path"
    dump_windows >> "$resurrect_file_path"
    dump_state   >> "$resurrect_file_path"
-   ln -fs "$(basename "$resurrect_file_path")" "$(last_resurrect_file)"
-    if ! cmp -s "$resurrect_file_path" "$(last_resurrect_file)"; then
-       ln -fs "$(basename "$resurrect_file_path")" "$(last_resurrect_file)"
-    else
-        rm "$resurrect_file_path"
-    fi
  if capture_pane_contents_option_on; then
      mkdir -p "$(pane_contents_dir)"
      dump_pane_contents

---

...Also, it would be nice to have config option in resurrect to not save active window marks '*' and  window activity marks '#' and '-'. IMHO they hardly deserve saving, but change too often.

**Comment by Kriechi** [comment]
It is hard to tell what actually changed (+ or - lines missing?)
Could you please format your patch with a line containing three backticks before and after?
https://help.github.com/articles/creating-and-highlighting-code-blocks/
Thanks!

**Comment by vburdo** [comment]
Hi,

Sorry for screwed patch. Here is correct one.
```
--- a/scripts/save.sh
+++ b/scripts/save.sh
@@ -259,7 +259,11 @@ save_all() {
 	dump_panes   >> "$resurrect_file_path"
 	dump_windows >> "$resurrect_file_path"
 	dump_state   >> "$resurrect_file_path"
-	ln -fs "$(basename "$resurrect_file_path")" "$(last_resurrect_file)"
+    if ! cmp -s "$resurrect_file_path" "$(last_resurrect_file)"; then
+	    ln -fs "$(basename "$resurrect_file_path")" "$(last_resurrect_file)"
+    else
+        rm "$resurrect_file_path"
+    fi
 	if capture_pane_contents_option_on; then
 		mkdir -p "$(pane_contents_dir)"
 		dump_pane_contents
```

**Comment by bruno-** [comment]
Thanks @vburdo this patch is applied via b1f3df21e9889e7324951e46be0249a5758dd9e1
