### ISSUE TITLE
vim session opened by file manager doesn't get restored

### ISSUE THREAD

**Issue by ngoonee** [tmux-plugins/tmux-resurrect#164]
So my habit has been to browse using rangerfm to my project directory and open files for editing within the file manager.

I've added ranger appropriately to tmux-resurrect, but on a restart it opens the file manager (to the correct directory) but not the vim instance I had been using for editing.

Is this possible, or do I have to change my habits by opening files in vim directly from zsh?

**Comment by bruno-** [comment]
Having your tmux-resurrect `last` file would help here, but based on what you said I think tmux-resurrect saves and restores just ranger. Here's how I think the process hierarchy looks like:


```
tmux
  -> your shell (bash?)
     -> ranger
         -> vim
```

tmux-resurrect saves whatever is opened **in your shell** which is ranger in the above example. It can't know what other processes is ranger manipulating with.

**Comment by ngoonee** [comment]
Yes, that's exactly it. In the time since I've 'resigned' myself to not being able to get it working that way (at least unless I can get cooperation from rangerfm, something which i didn't feel was worthwhile pursuing anyway).

Closing as `not-a-bug`.
