### ISSUE TITLE
"tmux-resurrect" download fail

### ISSUE THREAD

**Issue by apasashkov** [tmux-plugins/tmux-resurrect#165]
After trying to install via resurrect via tpm the following error emerges (after i hit prefix + Shit + I):

home/anton/.tmux/plugins// is not writable!                           
Already installed "tpm"
Installing "tmux-resurrect"
  "tmux-resurrect" download fail

Tried to install manually and got the message SESSION SAVED but when I restore it wrote something like NO RESTORE FILE IS FOUND

Maybe there is a problem with permissions. 
Any help will be appreciated. Thank you in advance!

**Comment by LukaK** [comment]
Seems your permissions for plugins folder are too restrictive and tpm can't install tmux-resurrect.

Try `chmod 755 /home/anton/.tmux/plugins` and retry installation with tpm.

**Comment by bruno-** [comment]
@apasashkov I think @LukaK provided a good response.

**Comment by dimitur2204** [comment]
> Seems your permissions for plugins folder are too restrictive and tpm can't install tmux-resurrect.
> 
> Try `chmod 755 /home/anton/.tmux/plugins` and retry installation with tpm.

That was the problem for me on mac as well
