### ISSUE TITLE
Saving environment to a file dependant on hostname

### ISSUE THREAD

**Issue by przemyslslaw** [tmux-plugins/tmux-resurrect#167]
I'd like to use the `tmux-continuum`, but I work on multiple machines that have a shared networked file system, so on restore the environments could (unintentionally) get swapped between machines, because the hostname is not in the file name and `tmux-resurrect` does not know on which machine was the environment saved. Is there any workaround for that?

Generally, wouldn't it be useful to choose the environment name (file name) on save/restore to switch between different tmux environments? I'd definitively use such functionality.

Either way, great plugin, thanks! :)

**Comment by wiscodisco** [comment]
I'm in a similar situation and would very much appreciate this functionality

**Comment by bruno-** [comment]
> so on restore the environments could (unintentionally) get swapped between machines

I'm not totally familiar with the shared networked file system, but does this mean these different machines have the same home dir and they would all share `~/.tmux/` dir as well?

My first thought is that even tho these machine share a file system on `/some/path/somewhere` they each have a separate `$HOME` and `$HOME/.tmux/`. If yes, then I think tmux resurrect (and tmux continuum) saving on each machine should be good.

If these machines share `$HOME`, then I'm mindblown.

> Generally, wouldn't it be useful to choose the environment name (file name) on save/restore to switch between different tmux environments?

This is possible, but you have to manually do this. `tmux-resurrect` saves files to `~/.tmux/resurrect/tmux_resurrect_*.txt`. The `~/.tmux/resurrect/last` file is a symlink that points to the specific `tmux_resurrect_*` file that will be restored.  The process of manipulating the `last` file is relatively simple and is described here: `https://github.com/tmux-plugins/tmux-continuum/blob/master/docs/faq.md`

For example, you can also use it for the purpose of restoring to an earlier point in time.

**Comment by comaniac** [comment]
Here is the simplest workaround if I understood your question correctly. In order to let tmux-resurrect recognize the saved sessions on different machines, you can let tmux-resurrect save sessions based on the hostname. Specifically, you can modify scripts/helpers.sh:1:

default_resurrect_dir="$HOME/.tmux/resurrect/"

This line specifies the directory to store the sessions. Simply change this line to:

default_resurrect_dir="$HOME/.tmux/resurrect/$(hostname)"

so that the saved session on different machines with different hostnames would be totally separated. Correct me if there has any problem.

**Comment by bruno-** [comment]
Yea, also the user can manually set resurrect dir by setting `@resurrect-dir` variable in `.tmux.conf`.
Example: `set -g @resurrect-dir '$HOME/.tmux/resurrect/machine'`

I think `$(hostname)` in tmux variable above won't work. Also I don't think using `$HOSTNAME` as a variable would work too. Best best is to set it literally to your machine name.

**Comment by bruno-** [comment]
Hey guys, based on @comaniac 's suggestion using `$HOSTNAME` is now allowed in `@resurrect-dir` option via fbed36ad0e813d71a3f2751e50c8bfd057f15598. Refer to the updated docs here: https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/save_dir.md

I think this problem now has a proper solution so I'll close the issue. Please reopen if you have any other concerns.

**Comment by fullstopslash** [comment]
It would seem that $HOSTNAME on Macs can change based on the current connected network. from HOSTNAME, to HOSTNAME.local, and so on.  $HOST seems to stay the same through network changes.
