### ISSUE TITLE
save with zoomed window leads to flickering

### ISSUE THREAD

**Issue by Ahg4goo9** [tmux-plugins/tmux-resurrect#176]
Wenn I zoomed into a pane and trigger save it zooms out and back in again. This is annoying if you use tmux-continuum, too, because the pane flickers every couple of minutes.

**Comment by henrebotha** [comment]
I've experienced this for months now. It's become an issue now because vim doesn't react appropriately to the fast flicker, leaving it squashed even after the second zoom in.

**Comment by henrebotha** [comment]
Here's a really ugly asciicast demonstrating it: https://asciinema.org/a/epbq20qcitdu4ps46ni5ro0a0

**Comment by bruno-** [comment]
Guys, I can confirm this is not perfect. I've tried optimizing this as much as I could a while ago, but the flicker was still there (much reduced tho).

The strategy `tmux-resurrect` uses is:

1. save which pane is zoomed and which one is not
2. unzoom to save each pane's dimension, then zoom again

The core problem is that we have to unzoom to get each pane's dimension! The pane dimensions aren't saved properly (by tmux) if pane is zoomed.

I'd very much accept a PR if someone can/knows how to improve this. Here are some specific things that could be done:

- I optimized this on tmux 1.9, and we're now on tmux 2.5. Maybe the core problem was fixed? Maybe we don't have to unzoom and
- If core problem is still present on latest tmux, report a bug in tmux and see what tmux maintainers say?
- If nothing, the relevant piece of code is here: https://github.com/tmux-plugins/tmux-resurrect/blob/5722856e54aa81fa419694fcf326231f1617cc78/scripts/save.sh#L224-L230 maybe someone can optimize?

**Comment by woutgg** [comment]
This is troublesome for me as well as it does not play well with my prompt (zsh, with right-aligned text).
I *think* the core problem in tmux has been fixed, so unzooming is no longer needed.

A quick test (with tmux 2.6) with the zoom toggling commands removed seems to confirm this.

**Comment by bruno-** [comment]
Great news. Do you want to submit a PR that removes window zoom toggling from this plugin? No need to have support for older tmux versions.

**Comment by woutgg** [comment]
The PR removes the zoom toggling and adds a zoomed pane to the tests to check whether it is saved and restored correctly.
