### ISSUE TITLE
Proposal/Request store ranger session

### ISSUE THREAD

**Issue by tigerjack** [tmux-plugins/tmux-resurrect#183]
As per the title, it could be great to have tmux-resurrect store the [ranger](https://github.com/ranger/ranger) session in a pretty similar way to the vim sessions. Do you think it could be possible/feasible? Thanks in advance for your help and your great tool.

**Comment by bruno-** [comment]
Hi,
this depends on ranger's possibilities only. I'm not using that tool so I really don't know.

But, given that it is possible and that the command to restore ranger's session is `ranger --restore` (I'm making this up), you'd then be restore its session with something like this:

```
set -g @resurrect-processes '"ranger->ranger --restore"'
```

The above option specifies to call command `ranger --restore` whenever `ranger` is detected. Hope this helps.

Doing issues cleanup so will close this one as it's not really a problem. Feel free to ask more if you need help.

**Comment by tigerjack** [comment]
Thanks @bruno- for the suggesion. What if instead the application behaviour is lightly different, i.e.
- to save the current session press F10
- to restore the session, simply relaunch the application.

So in my case, when storing a tmux session, I'd like to send the F10 signal to all the ranger session; then, when restoring the tmux session, I'd like to simply execute `ranger` in the window where it was opened.

**Comment by bruno-** [comment]
> So in my case, when storing a tmux session, I'd like to send the F10
> signal to all the ranger session;

Oh, I see.. didn't know 'F10' saves ranger session. Currently we don't
have any logic that performs 'work' when we save tmux's sessions.
Most of the 'work' happens during the restore.

I'm curious, why can't ranger dump the session at the time it's
quitting? This would be the workflow:

- you save tmux sessions (no interaction with ranger happens)
- You kill tmux with `:kill-server`. Tmux starts killing all the
  running processes. ranger detects it's being closed (via hook) and
  saves its state and then quits
- when tmux is restored all should work fine
