### ISSUE TITLE
[Suggestion] Choose another backup directory

### ISSUE THREAD

**Issue by falzard** [tmux-plugins/tmux-resurrect#185]
For those who use byobu, you could add a config setting to change the directory to whatever we want.

Tmux uses:
~/.tmux/resurrect/

But we could put it in:
~/.byobu/.tmux/resurrect/

**Comment by bruno-** [comment]
Hey,
you should be able to do that via `@resurrect-dir` option. I think something like this in your `.tmux.conf` file should do the trick:

```
set -g @resurrect-dir '~/.byobu/.tmux/resurrect/'
```

**Comment by bruno-** [comment]
I think the above should solve this request. Doing some issues cleanup so gonna close this one. Pls reopen if you have other issues.
