### ISSUE TITLE
Autosave on poweroff

### ISSUE THREAD

**Issue by GenaBitu** [tmux-plugins/tmux-resurrect#186]
I am working on a remote server and would like to use the (I know, experimental) feature of bash history saving. I now run
```zsh
my_program;sudo poweroff
```
I would like to save the tmux session just before the poweroff, so that if anything goes awry with `my_program`, I can inspect the bash history (and possibly the error messages) when I reconnect to the machine. So ideally, I would like for the session to be saved when closing tmux, either automatically (AFAIK tmux-continuum doesn't have this option) or by running something like
```zsh
my_program;tmux savesession;sudo poweroff
```
Is that possible?
Thank you

**Comment by tolgraven** [comment]
The save session keybind just does `run-shell $TMUX_PLUGIN_MANAGER_PATH/tmux-resurrect/scripts/save.sh`

**Comment by bruno-** [comment]
@GenaBitu what @tolgraven said is you can invoke the saving manually via script from the command line and it should do the job.

If you installed this plugin via default options then `~/.tmux/plugins/tmux-resurrect/scripts/save.sh` should do it.

I think the above should solve this guys. Gonna close the issue as there's so many.. but please do reopen if you have any problems.
