### ISSUE TITLE
Undo Feature

### ISSUE THREAD

**Issue by aaiezza** [tmux-plugins/tmux-resurrect#188]
Great plugin! Works great!
However, after rebooting my system, I meant to restore my tmux environment like I have done successfully many times before, but I accidentally **saved** my blank tmux environment instead of **restoring** it.
Is there an "undo" feature I am missing, or does one not exist?
If not, how difficult would this be to implement?
Thanks,
Alex

**Comment by chuyik** [comment]
**Restoring a previously saved environment**

Here are the steps to restore to a previous point in time:

- make sure you start this with a "fresh" tmux instance
- `$ cd ~/.tmux/resurrect/`
- locate the save file you'd like to use for restore (file names have a timestamp)
- symlink the `last` file to the desired save file: `$ ln -sf <file_name> last`
- do a restore with `tmux-resurrect` key: `prefix + Ctrl-r`

**Comment by aaiezza** [comment]
I had no idea! Thank you.
