### ISSUE TITLE
[Feature] Support for multiple profiles?

### ISSUE THREAD

**Issue by AnthonyWC** [tmux-plugins/tmux-resurrect#204]
Any plan to support for multiple profiles?

**Comment by bruno-** [comment]
Hi,
thanks for the interest.

This plugin stores the main "state" file in this dir `~/.tmux/resurrect/`. Whenever you save your environment, a new file is created there. The most recent save is symlinked to `~/.tmux/resurrect/last`.

You can get very far with your request if you're willing to manually manage state files in `~/.tmux/resurrect/`. For example, you'd need to identify which "state" file you want to restore, symlink it to `~/.tmux/resurrect/last` and then restore. It's pretty basic scripting stuff.

All this said, there are no plans to "officially" support the above workflow. Everyone that requested this that I've talked to wants this for some legacy, suboptimal reasons, example: ppl that have used tmuxinator before.
