### ISSUE TITLE
zsh: bad option: -L

### ISSUE THREAD

**Issue by noscript** [tmux-plugins/tmux-resurrect#218]
When saving shell history:

```sh
$  fc -lLn -64 > '~/.tmux/resurrect/zsh_history-0:1.1'
zsh: bad option: -L
^E fc -R '~/.tmux/resurrect/zsh_history-0:1.1'

$ zsh --version
zsh 5.0.7 (x86_64-pc-linux-gnu)
```

**Comment by noscript** [comment]
I guess `-L` was introduced in some later versions. Would be great to mention the minimal zsh version for saving history feature.

**Comment by imageslr** [comment]
I met the same problem and I'm using the same zsh with you.

**Comment by imageslr** [comment]
How did you fix the proble? @noscript

**Comment by noscript** [comment]
I think I upgraded to a newer zsh. @imageslr what is your zsh version?

**Comment by imageslr** [comment]
Exactly same version with you. @noscript  And it works in bash.

**Comment by imageslr** [comment]
What's your zsh version now?

**Comment by noscript** [comment]
```
$ zsh --version
zsh 5.7.1 (x86_64-debian-linux-gnu)
```

**Comment by imageslr** [comment]
After excuting `omz update`, my zsh version still is 5.0.7(x86_64-pc-linux-gnu). 

But I found tmux-resurrect still works even there are errors displayed.

Thanks for your help!

**Comment by noscript** [comment]
I'm not a user of ohmyzsh but I think `omz update` won't update zsh and you should rely on your linux distribution package manager instead.

If `-L` flag is not supported then pane history is probably not restored. There is still the default zsh history, so not a big deal.

**Comment by imageslr** [comment]
Thanks a lot. These information is very helpful.
