### ISSUE TITLE
Issue with restoring programs which are run with full path

### ISSUE THREAD

**Issue by thefallenidealist** [tmux-plugins/tmux-resurrect#226]
Nvim session will not be restored if nvim is started with path, eg: `/usr/local/bin/nvim`.
Similar behavior is noticed with `man` on my OS, eg, `man ls` in ps will be shown as `/bin/sh /usr/bin/man ls`.

If I apply this kludge then restoring will work:
```diff
scripts/process_restore_helpers.sh
-       local user_processes="$(get_tmux_option "$restore_processes_option" "$restore_processes")"
+       local user_processes="vi vim /usr/local/bin/nvim /bin/sh\ /usr/bin/man"
```

I'm using
- tmux 2.6
- zsh 5.4.2 (amd64-portbld-freebsd11.0)
- FreeBSD 11.1-RELEASE-p4

A little bit OT:
How difficult would be to remember position in man page?

**Comment by bruno-** [comment]
This is ok behavior. This plugin will restore `nvim` process, not `/usr/local/bin/nvim`. Sure, we humans know it's the same program, but this script doesn't (and I don't think it should attempt to).

If you want to make this work, this option should do the trick: `set -g @resurrect-processes '~nvim ~man'`

More about restoring programs here https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_programs.md

**Comment by thefallenidealist** [comment]
Yes, you are right, the tilde did the trick, thanks!
Sorry for the noise, somehow didn't see the '~' on the wiki.
