### ISSUE TITLE
Where is the path of the saved config (file or files) that `tmux-resurrect` generates?

### ISSUE THREAD

**Issue by cabaalexander** [tmux-plugins/tmux-resurrect#227]
The porpuse for this is that I'm doing a develop environment with vagrant and I want the config for the panes to persist.

With that I can make a copy out of the vagrant machine or something :')

I don't know if some time in the future the directory of some pane/window/session might change and then causing not a normal behaviour 🤔 But that's another story.

**Comment by bruno-** [comment]
Hi,

I think this doc might help with answering your question: https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/save_dir.md

**Comment by FWinkler79** [comment]
If you are on Mac, you might also find that (other than what the documentation suggests) `tmux-resurrect` stores its files here:

```
~/.local/share/tmux/resurrect/
```
