### ISSUE TITLE
How can we restart tmux and restore vim sessions without all the swapfile warnings

### ISSUE THREAD

**Issue by dylan-chong** [tmux-plugins/tmux-resurrect#228]
it's rather annoying if i change something in my configuration and need to do something like a `kill-server`, but that means all my vim sessions will have warnings for each file that there is a swapfile. is there a nicer way to restart tmux than `kill-server`?

**Comment by bruno-** [comment]
Hi,

I think putting this in your `.vimrc` will solve your problem: `set nobackup noswapfile`
I'm running with this for a couple years now and never had a problem (eg. I never thought: "oh I wish I had a swap or a backup file now").

`kill-server` is a forceful way to kill all the programs running inside tmux. I'm sure a unix purist somewhere will tell you how bad that is. If you want to gracefully kill programs then I think you'd have to go pane-by-pane and quit each program. That said, I've been using `kill-server` for years now and never noticed any issues.

**Comment by dylan-chong** [comment]
Haha this is hilarious! I'll give it a try though

**Comment by dylan-chong** [comment]
I forgot to reply to this thread. I have set `set nobackup noswapfile` as well as set up auto save so when my terminal unfocuses the file save, and in the past year and a half i've never lost anything due to the lack of swap files.
