### ISSUE TITLE
Question: How do I unlink/ungroup sessions?

### ISSUE THREAD

**Issue by fearphage** [tmux-plugins/tmux-resurrect#231]
I'm not sure how buy I have grouped sessions. I would to undo that functionality. I looked in the docs directory and didn't see anything mentioned. How do I ungroup sessions?

**Comment by Evolter** [comment]
Hi fearphage,

First of all I think this question should be asked on a correct project: https://github.com/tmux/tmux

Secondly, I was looking about ungrouping myself and search engine pointed me at this ;)
I did not find a more convenient way so far, but what you can do is to kill the session you are in with:
`:kill-session` or while outside of that session `tmux ls` find the name/id of grouped sessions and kill them with `tmux kill-session -t ${session_to_kill}` so you will be left with only one. Note that this won't kill your windows and panes as long as at least one session from that group will be left alive.

In case if you have more than 2 sessions in one group and want to leave just one `tmux kill-session -a -t ${session_to_leave}` (kill all but specified). **Very important** if you have more groups or sessions outside of the group you want to get rid off, do NOT do this as this will kill them as well! Instead kill them one by one without `-a` flag.

**Comment by fearphage** [comment]
Thanks. Sorry for the misplaced issue.
