### ISSUE TITLE
Correctly remember the "no session" state.

### ISSUE THREAD

**Issue by pvaret** [tmux-plugins/tmux-resurrect#232]
Currently, if I close my last tmux session, tmux-resurrect does not take that into account, and restores that session's last known state the next time I start tmux.

It would be nice if tmux-resurrect could update its state to "no session, nothing to actually resurrect" or somesuch when I close the last session.

(Also: thanks for this awesome plugin! Keep up the good work!)

**Comment by bruno-** [comment]
Hi,
I don't think we can save the "no session" state.

You probably also have https://github.com/tmux-plugins/tmux-continuum installed and it's periodically saving the state. It saves before you kill the last session, and it doesn't save after you kill it.
So, the next time you restore it restores "older state". Does this assumption sound correct?

If the above assumption is correct I think we'd rather let the users worry that much. I'm sure the request could be satisfied with the next tmux hooks feature, but it would require a big plugin redesign (maybe a rewrite) and I'm not up for it now.

**Comment by pvaret** [comment]
Yup, that sounds like a pretty good assumption, and I indeed use tmux-continuum (admittedly I don't fully grasp where tmux-resurrect's responsibilities stop and tmux-continuum's starts).

So be it, then! Thank you for taking the time to reply. I'll close this ticket now, but please let me know if you'd like it reopened as a feature request for the future.
