### ISSUE TITLE
Is there a way to restore NVIM/VIM session using a custom file?

### ISSUE THREAD

**Issue by cabaalexander** [tmux-plugins/tmux-resurrect#236]
The Obsession Plugin lets you rename the file for the session. 

Line in the Obssession doc here -> https://github.com/tpope/vim-obsession/blob/master/doc/obsession.txt#L9

I've created a function that checks if you are in a session using my custom filename (`.session.vim`).

You can take a look at this gist with the function -> https://gist.github.com/cabaalexander/5010327cf3866e11c1137af8d7d41b44

The purpose for the dot on the filename is to make it hidden from nerdtree/ctrP/etc 🤷‍♂️ 

For you to use that custom filename you would need to use

```bash
$ nvim -S .session.vim
```

If not it will 💥 (It will not find the `Session.vim` default file)

I was thinking that maybe we could pass an optional filename representing the custom filename in the case we would like to use one 🤔 Like the example below 👇 

```
@resurrect-strategy-nvim 'session' '.session.vim'
```

Does this make sense?

Hi 👋

**Comment by cabaalexander** [comment]
I was reading a little bit more about tmux. ( `@resurrect-strategy-nvim` is a window variable being set globally on tmux via `setw -g` )

Which now I think by creating another with the name of the session file would be the way to go 🤔 

i.e. `@resurrect-strategy-nvim-session-filename '.session.vim'`

**Comment by bruno-** [comment]
Hi,

`nvim` and `vim` strategies are in [`strategies/` dir](https://github.com/tmux-plugins/tmux-resurrect/tree/master/strategies).

You can code another strategy any change it via tmux global var. I don't think a strategy that uses just a changed session file name would be accepted to this repo tho. The request is too niche.. and frankly, you should stick to the default file name `Session.vim`.

**Comment by cabaalexander** [comment]
I'm kinda new on contribute to github (or trying to) 😅

I thought of that too. I did work around that by sticking to the `Session.vim` file and addding it to my global `gitignore`. Here the line on my repo -> [Go](https://github.com/cabaalexander/devagrant/blob/master/sync/nvim/autoload/utils.vim#L17)

Well,  really really thank you for your time. I think this can be closed. :D

**Comment by bruno-** [comment]
Yep, sticking with the default `Session.vim` and adding it to the global `gitignore` is the way to go.
