### ISSUE TITLE
Restoring vim with multiple tabs

### ISSUE THREAD

**Issue by thiagotei** [tmux-plugins/tmux-resurrect#238]
Hi there,

I had a vim with multiple tabs open and would like to open them all when restoring. 
Is it supported?

Thanks

**Comment by darkcoderrises** [comment]
You can couple up tmux-resurrect with [vim-session](https://github.com/thaerkh/vim-workspace). Add the following line in your tmux.conf `set -g @resurrect-strategy-vim 'session'`.
Also check this out set -g @resurrect-strategy-vim 'session'

**Comment by thiagotei** [comment]
I've tried that and did not work. It restore with only one buffer, which I think was the first one opened, a no tabs at all.
Besides, every time I restore the vim sessions the files appear with a bunch of empty lines in halfway down the screen. I have to close and open all to get rid of that space. Maybe I should open another issue for that.
Thanks

**Comment by dylan-chong** [comment]
@thiagotei Did you call `:Obsession` inside vim?

**Comment by thiagotei** [comment]
No. What is `:Obsession`? What kind of file arguments?

**Comment by dylan-chong** [comment]
Read the docs https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_vim_and_neovim_sessions.md

**Comment by dylan-chong** [comment]
No, the point of saving the session is to save multiple tabs/splits. You only need to call Obsession once . This information should be in the vim-obsession documentation

**Comment by thiagotei** [comment]
Thanks!
