### ISSUE TITLE
“be careful” … of what?

### ISSUE THREAD

**Issue by isomorphisms** [tmux-plugins/tmux-resurrect#250]
`~/docs/restoring_programs.md` says:

> 
> - Restore **all** programs (be careful with this!):
> 
>         set -g @resurrect-processes ':all:'
> 

It would be helpful to be more specific about what can go wrong if one does this.

**Comment by chrysn** [comment]
Concrete drive-by suggestions:

> Be *very careful* with this: tmux-resurrect can not know which programs take which context, and a `sudo mkfs.vfat /dev/sdb` that was just formatting an external USB stick could wipe your backup hard disk if that's what's attached after rebooting.

**Comment by bruno-** [comment]
PR for docs improvement is welcome
