### ISSUE TITLE
tmux ressurect fills screen with calls to commands

### ISSUE THREAD

**Issue by dareenzo** [tmux-plugins/tmux-resurrect#263]
Hi,

I'm using this plugin and as time goes by it inserts calls to some plugin related commands on my window, as seen in the screenshot bellow.

Is this normal? Is there a way I could make it less intrusive? Did I somehow misconfigure the plugin?

Thanks

<img width="1680" alt="screen shot 2018-08-02 at 16 43 59" src="https://user-images.githubusercontent.com/6130991/43591286-4b8eed1c-9673-11e8-8439-21fa1e5c8e73.png">

**Comment by bruno-** [comment]
I think that's a side-effect of this feature https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_shell_history.md

I personally also really dislike that those commands are inserted and would prefer to remove this feature from the plugin altogether.

Please close the issue if turning off the feature above helped.

**Comment by dareenzo** [comment]
Turning the feature off solved the issue.

Thanks

**Comment by liamaharon** [comment]
@dareenzo  I've found another way to keep history of commands I make inside my tmux panes: 

https://askubuntu.com/a/339925
>You have to preserve bash history in multiple bash shells. To do this, be sure that you have the following lines in your ~/.bashrc file:
>```
># avoid duplicates..
>export HISTCONTROL=ignoredups:erasedups
>
># append history entries..
>shopt -s histappend
>
># After each command, save and reload history
>export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
>```

it's not perfect as all panes share the same history, but it's **much** better than nothing

hope this helps someone
