### ISSUE TITLE
Tmux resurrect file not found!

### ISSUE THREAD

**Issue by fdelacruz** [tmux-plugins/tmux-resurrect#268]
Running on macOS Mojave
Tmux 2.7
Homebrew 1.7.2-55-gdaf515f
Homebrew/homebrew-core (git revision 9b5d; last commit 2018-08-28)

My tmux.conf:
```
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```
(Prefix + Ctrl-s) reports it saves, but there is nothing inside ~/.tmux/resurrect so of course when I try to restore (Prefix + Ctrl-r) I get the dreaded "Tmux resurrect file not found!"

I should add that ~/.tmux permissions seem normal (755):

> drwxr-xr-x   3 fdelacruz  staff    96B Aug 24 06:19 .tmux

If I run tmux as root (sudo tmux) resurrect works, saving into the root directory '/'. root can save and restore envs. normal users saves don't take hold and can only restore what root envs has saved.

**Comment by fdelacruz** [comment]
Why does Prefix  + Ctrl-s say that it saved the Tmux environment instead of throwing an error??

**Comment by fdelacruz** [comment]
Is there way to turn on a verbose mode in order to see what’s (not) happening and why??

**Comment by fdelacruz** [comment]
So it occurred to me to run as root using (sudo). 
Resurrect works beautifully. Even though I don't see where it is saving its file.

**Comment by fdelacruz** [comment]
Ok, so I found the saved files in the root (/) directory.
I installed Tmux using Homebrew and never had permission issues until now.

**Comment by fdelacruz** [comment]
The problem was my computer's hostname!!
Mine had a comma (macbookpro12,1) in the name. 
Go figure!!

**Comment by chikamichi** [comment]
Resurrecting (!) an old issue, just to mention that for some reason, I had to `touch ~/.tmux/resurrect` in order to make the plugin work.
