### ISSUE TITLE
resolution-specific layout memory idea

### ISSUE THREAD

**Issue by atsepkov** [tmux-plugins/tmux-resurrect#276]
**Disclaimer**
This is probably beyond the intent/scope of original plugin, but this plugin comes closest to allowing such functionality so I figured I'd start the discussion here first so see if I could get some support/feedback. It may make sense to fork a new plugin from tmux-resurrect for this to keep code-bases clean but I didn't want to be reinventing the wheel or breaking compatibility with tmux-resurrect itself.

**Use Case**
A few months ago I purchased a couple ultrawide monitors, these things are great for fitting more content on the screen. Problem is that my monitors at work are still 1080p, so I'm stuck between having my panes squished on the work monitors or having them inefficiently laid out on home monitors. I would like tmux to remember the layout based on monitor resolution (and the only plugin that does any sort of layout memory is this one). There are also edge cases I'd need to consider (like deciding where to put additional panes created in different layout or what to do with ones that were removed in different layout).

**Simplified Case**
At the most basic level, my tmux on 1080p is basically 2 columns with varying number of rows in each one, and 3 columns on my ultrawide monitors. I basically treat it like a book. I don't know how many other developers use tmux the same way, however. Perhaps adding a concept of a "page" to each window would be good enough, where each page would contain multiple panes, and the window would display the number of pages based on its size, allowing user to "flip" between pages to do operations like "diff", etc.

**Comment by bruno-** [comment]
Hey, thanks for describing your use case.

Based on your description where you need 2 columns @ 1080p and 3 columns @ ultrawide monitor it's as if you need "responsive layouts". This seems like an interesting and  hard problem. And yea, def out of scope for this plugin. This plugin focuses on saving and restoring tmux on a **single machine**.

I encourage you to fork the plugin and try to implement a solution based on your needs. If you get something working, feel free to publish it under different name. You don't have to make any attributions 👍
