### ISSUE TITLE
Automatically restore multiple sessions to multiple shells?

### ISSUE THREAD

**Issue by rcywongaa** [tmux-plugins/tmux-resurrect#298]
Suppose I have 2 shells, each running a tmux session (e.g. shell A running session 1, shell B running session 2).  After tmux-saving and closing the 2 shells and perhaps rebooting, I would like to return to the previous state with 2 shells open, one running session 1 with, one running session 2.

If I manually open 2 shells**, shell C and shell D, is there a way to have resurrect automatically attach session 1 to shell C (or D) and session 2 to shell D (or C)?

\** Or better yet, I only manually open 1 shell, run restore, and resurrect automatically opens any additional shells it needs to attach the saved sessions
Similar to how Chrome restores tabs in different windows

**Comment by studgeek** [comment]
From what I have  seen tmux will save and restore all sessions. Opening them is up to you though. You could probably write a simple bash script that lists your tmux sessions and opens a terminal for each one.

**Comment by rcywongaa** [comment]
I achieved a partial solution where you still had to manually open the terminal emulators, but each terminal would automatically be restored to one of the saved sessions.

I put this in my `.zshrc`
```
if [[ -z "$TMUX" ]]; then
    if [[ -n "$(tmux list-session | grep -v 'attached')" ]]; then
        tmux a
    else
        tmux new
    fi
fi
```
And also had to apply this patch (https://github.com/tmux-plugins/tmux-resurrect/issues/101#issuecomment-486982469)
