### ISSUE TITLE
Save program currently running in the pane

### ISSUE THREAD

**Issue by bruno-** [tmux-plugins/tmux-resurrect#3]
Saving currently running program should be easy.

Restoring is trickier because we don't want to restore everything (think - long running jobs, servers etc). There should be a conservative list of programs that should be automatically started, and the user should be able to enhance it.

List of programs that should be restored:
- vim
- man
- less
- more
- emacs?
- rails console
- pry
- rails server???

**Comment by knight42** [comment]
Hi @bruno- , thanks for writing such an amazing plugin, it's awesome! 
But now I encounter a problem, some programs(i.e ipython, python interactive shell) can't be resurrected correctly on my machine though some can(such as vim, emacs, man). When I save an "ipython session", the information saved as following:
```
pane	0	1	:python3	1	:*	1	:/home/knight	1	python3	:/usr/bin/python3 /usr/bin/ipython --no-autoindent --no-confirm-exit
pane	0	2	:zsh	0	:-	1	:/home/knight	1	zsh	:
window	0	1	1	:*	cc3e,136x38,0,0,1
window	0	2	0	:-	cc3f,136x38,0,0,2
state	0	0
```
It seems all the necessary information has been saved, but when restoring, it just open a bare tmux window. What's the problem?

**Comment by bruno-** [comment]
Hey,
great, glad you like the plugin.

More about restoring programs has been written [in the readme here](https://github.com/tmux-plugins/tmux-resurrect#configuration). So, not all programs are restored by default for obvious security and computer resource issues..

Try putting this in your `.tmux.conf`:

    set -g @resurrect-processes '~ipython'

The above should restore a process if it contains string `ipython` (the tilde character at the beginning indicates a regex-like matching).

From what you pasted above, the process that is being saved in your case is `/usr/bin/python3 /usr/bin/ipython --no-autoindent --no-confirm-exit`. It contains `ipython` string so it should be restored.

Does that work?

**Comment by knight42** [comment]
Wow, thanks! It works like a charm! Sorry for my carelessness though...

**Comment by lmartak** [comment]
Thanks alot @bruno-, this saved my day!

I was also wondering, if I wanted to restore the `~ipython` process with the command in all its glory, (e.g. including output redirection) such as this: `jupyter lab --no-browser &>> ~/logs/jupyter.log`, what would be the correct way to combine the `""`, `->` and `~` notations? Or is it even possible currently?

Many thanks for your work on the plugin, I love it!
