### ISSUE TITLE
FR: Confirmation on restore

### ISSUE THREAD

**Issue by virusdave** [tmux-plugins/tmux-resurrect#302]
Feature request:  Require a confirmation on restore (ideally typing an all-caps YES or similar).
It's way too easy to accidentally hit <Ctrl-R> instead of <Ctrl-S>, and like with chrome browser, losing all state is catastrophic.  Chrome solves this by allowing a "require confirmation before closing everything" option as a safeguard.  This plugin should allow similar.

**Comment by virusdave** [comment]
(For that matter, a "confirm on save" option might be a good idea also)

**Comment by bruno-** [comment]
Saving never deletes previous "save checkpoints". The second point in this FAQ provides more info on this https://github.com/tmux-plugins/tmux-continuum/blob/master/docs/faq.md#faq

As for "restoring": I ran it accidentally a couple time, but it was never destructive (not saying it can't happen in any scenario). If restore detects your pane "x" is already created it will not mess with it.

If "destructive restore" and easy hitting `ctrl-r` worries you, I propose remapping this to something else, more info in `scripts/variables.sh`
