### ISSUE TITLE
Resurrect command is not working on Mac OSX

### ISSUE THREAD

**Issue by amrs-tech** [tmux-plugins/tmux-resurrect#305]
I use tmux 2.9, which is installed via Homebrew. My tmux is running properly but I didn't find any .tmux.conf file, so I created one based on a Stackoverflow answer. But my resurrect commands (ctrl+s / ctrl+r) doesn't seem to be working. I don't know even my tmux.conf was properly sourced or not ( I used `tmux source-file ~/.tmux.conf` )

**Comment by mannibis** [comment]
Are you doing Ctrl-B and THEN Ctrl-S? By default, the prefix is Ctrl-B for tmux unless you changed it which is doubtful based on your question.
It should say "Tmux environment saved!" at the bottom after saving. If not, then for some reason your conf isn't being loaded. You can also source it by doing Ctrl-B + : and then entering "source-file ~/.tmux.conf"

**Comment by shairyar** [comment]
Same here, i installed this plugin via `tpm` and prefix + ctrl + s does not seem to do anything, there is no message at all.

I installed `tmux` via `homebrew` and the version i have is `tmux 3.0a`

**Comment by burgessa23** [comment]
for me I see the save and restore messages, but restoring only yields the same as if I made a new Tmux session without restoring

**Comment by shairyar** [comment]
My problem was I was using a custom `tmux.conf.local` file and as per the [documentation](https://github.com/tmux-plugins/tpm/blob/master/docs/tpm_not_working.md#help-tpm-not-working) I have to list the plugins in following format

```
# List of plugins                                                                                                                                                                                 
set -g @tpm_plugins '          \                                                                                                                                                                 
tmux-plugins/tpm             \                                                                                                                                                                 
tmux-plugins/tmux-sensible   \                                                                                                                                                                 
tmux-plugins/tmux-resurrect  \                                                                                                                                                               '                                                                                                                                                                                                
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)                                                                                                                
run '~/.tmux/plugins/tpm/tpm'
```

After doing this the plugin is working just fine.

**Comment by eprislac** [comment]
ctrl-b ctrl-s just hides the powerline border for me

**Comment by l43lu** [comment]
any news on this issue?

**Comment by amrs-tech** [comment]
Sorry no updates and i stopped using tmux a while back. So closing this issue. Thanks to all who contributed their suggestions and opinions.
