### ISSUE TITLE
Can I save/restore tmux status by name?

### ISSUE THREAD

**Issue by Dizans** [tmux-plugins/tmux-resurrect#324]
Keeping different status such as work/study/... not only the last so that users can launch tmux and go to familiar status conveniently.

for example:
    prefix + Ctrl-s --name work
    prefix + Ctrl-s --name study

when i launch tmux , if i want to go to work/study status: prefix + Ctrl-r --name work/study.

I know some complex bash scripts can do this work.Does tmux-resurrect support this now?

**Comment by cameron** [comment]
Not to muddy the waters too much, but I've been using a dash of zsh to "resurrect" (that is, not using the plugin, but same idea) tmux sessions in directories that contain a .tmux script, which creates the workspace from scratch if none exists. 

Named- and directory-associated workspaces both seem like nice features; would love to hear from anyone in case the directory feature has eluded me...
