### ISSUE TITLE
Allow XDG standards on save-dir.

### ISSUE THREAD

**Issue by dansdantas** [tmux-plugins/tmux-resurrect#348]
Pretty much the title. I just want to use `$XDG_DATA_HOME/tmux/resurrect` as my save directory.

Thanks for your hard work.

**Comment by sgleizes** [comment]
You can do `set -g @resurrect-dir "$XDG_DATA_HOME/tmux/resurrect"`.
Note the double quotes.

The [doc](https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/save_dir.md) is misleading about this. This will work assuming that `XDG_DATA_HOME` is exported in the environment when your tmux configuration is loaded.

**Comment by bjornfor** [comment]
I think this should be re-opened. Being able to set `set -g @resurrect-dir "$XDG_DATA_HOME/tmux/resurrect"` isn't really supporting the XDG standard.

* Each user must find this themself and configure accordingly.
* As commented by @sgleizes, the doc says one cannot use arbitrary shell variables, so using that configuration is basically "undefined behaviour".
* Implementing the XDG spec means that "if $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used." (how would users do that without tmux-resurrect support?)

My config is now `set-option -g @resurrect-dir "~/.local/share/tmux/resurrect"`, but I wish I didn't have to do that.

**Comment by bruno-** [comment]
Agreed. This should be the order priority:

- `@resurrect-dir` tmux var
- `TMUX_PLUGIN_MANAGER_PATH` (from tpm is present) + `/resurrect/`
- `XDG_DATA_HOME` (if present) + `/resurrect/`
- `$HOME/.tmux/resurrect`

**Comment by bjornfor** [comment]
> XDG_DATA_HOME (if present) + /resurrect/

Nitpick, but perhaps use one of these instead of `/resurrect/`?
* `/tmux/resurrect/`
* `/tmux-resurrect/`

Oh, and more importantly think if XDG_DATA_HOME is unset, the default directory ~/.local/share should be used instead (ref. [the spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)). That would mean that `$HOME/.tmux/resurrect` is only used if it already exists, for backwards compatibility.

**Comment by erikw** [comment]
@bjornfor Exactly! In bash, this would be as simple as using 

```bash
${XDG_DATA_HOME:-$HOME/.local/share}
```

+1 for being XDG compliant without the need for configuration. Tmux is XDG compliant since [v3.1](https://raw.githubusercontent.com/tmux/tmux/3.1/CHANGES).

**Comment by MartyMcFlyInTheSky** [comment]
It should have been `$XDG_STATE_HOME` as it preserves a state. nvim shada files are also dropped there.

I added this to my tmux.conf:
`set -g @ressurect-dir "$XDG_STATE_HOME/tmux"`

It only expands correctly with double quotes
