### ISSUE TITLE
Proposal for auto-save

### ISSUE THREAD

**Issue by pierot** [tmux-plugins/tmux-resurrect#35]
Would it be possible to set up auto save for tmux-resurrect.
Just two extra configuration settings: enable or disable autosave and autosave interval.

**Comment by bruno-** [comment]
Hey guys, a lot has been said... I didn't know you have issues with crashes so often. That certainly makes an autosave feature request more valid.

If someone wants to take action on this, I think a separate `tmux-resurrect-autosave` plugin could be made pretty easily. Here's the general idea:
- the key thing where you can "hook" is tmux's status bar. `status-right` is refreshed every `status-interval` seconds (15 by default). If for example string like this `#(autosave_script.sh)` is put in `status-right`, then that will execute `autosave_script.sh` every 15 seconds.
- you probably don't want to save every 15 seconds, so you build some simple mechanism to store the time of the last save and check if enough time passed till then. If enough time passed (a day?), then run  save (ta-da: tmux based cronjob).

As mentioned above, it's probably best this be a separate plugin (not included in tmux-resurrect). That way things are more maintainable and users don't have to fiddle with options. They just install `resurrect-autosave` and things just work.

If someone wants to take this I'd be glad to help with support and answering questions. When it's done, we can link the repo from this project's readme.

**Comment by markeissler** [comment]
@bruno The OSX crashes seem to be recent for me and possibly related to vmware + OSX 10.10.

I disagree that this should be a separate plugin. The feature is dependent upon tmux-resurrect after all. It would just be one more option: to enable or disable auto-save. If enable is set to 0 (minutes), then auto-save is off, anything other positive value would indicate the feature is turned on. Whether or not auto-save should be turned on by default is up for discussion--right now I'd say it probably should be on by default.

I can take a look at this once I'm satisfied with the history-buffer feature ([Save/Restore Buffers Feature #62](https://github.com/tmux-plugins/tmux-resurrect/pull/62)) I've been working on.

**Comment by bruno-** [comment]
> I disagree that this should be a separate plugin. The feature is dependent upon tmux-resurrect after all.

@markeissler I kinda agree with this. Also your "interface"/option description for this feature is good.

I proposed making this a separate plugin just to make the maintenance easier and offload it from `tmux-resurrect`.
I feel I'm lagging on a lot open pull requests and issues (yours included) and taking more code into this plugin certainly wouldn't help offloading this... No other reason than this, really.

**Comment by markeissler** [comment]
Hmmm. No worries @bruno! I've been lagging on making a couple of changes to my history-buffer patch. In the meantime, I've just been "using" the patch to see what needs improvement.

**Comment by markeissler** [comment]
Update: I've started working on this issue. It will combine my previous efforts on:

[Save/Restore Buffers Feature #62](https://github.com/tmux-plugins/tmux-resurrect/pull/62)

The feature aims to be as transparent to the user as possible.

**Comment by bruno-** [comment]
Hi guys, there's now a separate plugin that does auto saving [tmux-resurrect-auto](https://github.com/tmux-plugins/tmux-resurrect-auto).
I'd appreciate if someone can try it out and report if everything is okay.

Other than that I think this issue can be closed. If `tmux-resurrect-auto` has any issues let's open them in a that project.

**Comment by unphased** [comment]
Sweetness. You're the best, @bruno-

**Comment by bruno-** [comment]
Hi guys,
[tmux-resurrect-auto](https://github.com/tmux-plugins/tmux-resurrect-auto) just got a new feature: automatic restoring when tmux server is started.

Thank you for the kind words @unphased.

**Comment by cirosantilli** [comment]
tmux-ressurect-auto link is dead.

**Comment by dkns** [comment]
@cirosantilli I think it's called continuum now: https://github.com/tmux-plugins/tmux-continuum
