### ISSUE TITLE
After reboot, first split always goes to home directory

### ISSUE THREAD

**Issue by rcywongaa** [tmux-plugins/tmux-resurrect#354]
My `.tmux.conf`
```
set -g @continuum-boot 'on'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-vim 'session'
```

Steps to reproduce:
1. (in original split, let's call it split 1) cd to directory X
1. create split (let's call it split 2)
1. cd to directory Y
1. Save session
1. Close terminal
1. Open terminal
1. Restore session
1. Split 1 correctly restores to directory X, split 2 correctly restores to directory Y
1. Save session and close terminal
1. Reboot
1. Open terminal and restore session
1. Split 1 is in home directory, split 2 correctly restores to directory Y

This seems to only happen when the session name is 0

**Comment by bruno-** [comment]
You have this at the bottom of your `.tmux.conf` right?

    run -b '~/.tmux/plugins/tpm/tpm'

Can you try removing `-b` so you have this `run '~/.tmux/plugins/tpm/tpm'` and then see if this issue still happens?

**Comment by rcywongaa** [comment]
The last line of my `.tmux.conf` is already `run '~/.tmux/plugins/tpm/tpm'`

**Comment by rcywongaa** [comment]
Issue was due to a rogue `new-session` at the beginning of my `.tmux.conf`...
