### ISSUE TITLE
When restoring command containing path with spaces, path gets separated

### ISSUE THREAD

**Issue by frontierpsycho** [tmux-plugins/tmux-resurrect#358]
In a saved session, I had run the following command:

```
$ vim filename\ with\ spaces
```

Which opened an existing file in vim (`filename with spaces`). After restoring, vim had three new files open: `filename`, `with`, `spaces`.

Not sure it's possible to save and restore this :shrug:

**Comment by bruno-** [comment]
I just tested this and I confirm this is a problem.

The hard part is actually saving the command `vim filename\ with\ spaces`. I tried saving it with both `pgrep` and `ps` (default) [strategy](https://github.com/tmux-plugins/tmux-resurrect/tree/master/save_command_strategies) and it always turns as `vim filename with spaces`.

Maybe try with `set -g @resurrect-save-command-strategy 'linux_procfs'` if you're on linux.

**Comment by frontierpsycho** [comment]
Thanks for looking into it so quickly! Tried it just now and it didn't help.

**Comment by timmyjose** [comment]
This seems solve-able for the specific case of `<command> file with spaces`, but suppose we have flags et al involved in the command, such as `<cmd> <flag1> <flag2> file with spaces` (for a concrete example, `vim +100 my big log file`), then that becomes an intractable problem since it would entail actual knowledge of the command itself. 

For the simple case above, something like so would work to simply add double quotes around the file with spaces in its name (is `ps.sh`):

```
full_command() {
  cmd_line=$(ps -ao "ppid command" |
		sed "s/^ *//" |
		grep "^${PANE_PID}" |
    cut -d' ' -f2-)

  cmd=($cmd_line)
  if [[ "${cmd[0]}" == "vim" || "${cmd[0]}" == "nvim" ]]; then
    echo "${cmd[0]} \"${cmd[@]:1}\""
  else
    echo "${cmd[@]}"
  fi
}
```

**Comment by bruno-** [comment]
You can always create a command specific restore strategy like `strategies/vim_session.sh`

In case you have a command `vim foo bar` you cant just know if `foo bar` are two different files or if it's a file that contains space.

**Comment by pylipp** [comment]
> set -g @resurrect-save-command-strategy 'linux_procfs'

This did the trick for me! @frontierpsycho did you resource your `.tmux.conf` after having added the new line?
I'm on tmux 2.6, tmux-resurrect e482505

**Comment by frontierpsycho** [comment]
I believe I did. I might try again soon.

**Comment by frontierpsycho** [comment]
That does solve it for me too! I'll close the issue.
