### ISSUE TITLE
Use non-global option @resurrect-dir instead of global option @resurrect-dir, this will allow maintaining multiple independent resurrect sessions

### ISSUE THREAD

**Issue by reportaman** [tmux-plugins/tmux-resurrect#389]
This will solve https://github.com/tmux-plugins/tmux-resurrect/issues/246.

Having ``@resurrect-dir`` to be local to a session:

```
tmux set @resurrect-dir '/Users/amanmehra/.resurrect/home/Desktop/textfiles/grid-typesetting'
instead of
tmux set -g @resurrect-dir '/Users/amanmehra/.resurrect/home/Desktop/textfiles/grid-typesetting'
```

 is the only missing link in maintaining and working simultaneously on different $PWD based resurrect sessions.

Once you switch over to using session local ``@resurrect-dir``, please also close https://github.com/tmux-plugins/tmux-resurrect/issues/246. A user can then write a 10ish lines bash script to be able to maintain multiple tmux-resurrect tmux sessions.

**Comment by reportaman** [comment]
One option is to add a 3rd optional argument to get_tmux_option function in file [helpers.sh](https://github.com/tmux-plugins/tmux-resurrect/blob/master/scripts/helpers.sh):

```bash
get_tmux_option() {
	local option="$1"
	local default_value="$2"
    local showoptionswitch="${3:--gqv}"
	local option_value=$(tmux show-option $showoptionswitch "$option")
	if [ -z "$option_value" ]; then
		echo "$default_value"
	else
		echo "$option_value"
	fi
}
```

And a line in function resurrect_dir to:
```
		local path="$(get_tmux_option "$resurrect_dir_option" "$default_resurrect_dir" "-qv")"
```

This works! But with one caveat: tmux-resurrect saves all sessions. There should be an option to just store the current/focussed session in the "local" last session file.

**Comment by reportaman** [comment]
PR has been created: https://github.com/tmux-plugins/tmux-resurrect/pull/390

**Comment by bruno-** [comment]
As mentioned in #390 I encourage creating another plugin that focuses on saving/restoring individual sessions.
