### ISSUE TITLE
Buffer Restoration?

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [tmux-plugins/tmux-resurrect#395]
Is restoring the contents of the `tmux` buffer supported or planned to be supported? For example, if you open a session, run `ls`, close the session and restore that output, the output of `ls`, will not be saved and thus not restored. As it is in the `tmux` buffer, is there any plan to save and then reload the content of the `tmux` buffer into the restored session?

**Comment by danielkrajnik** [comment]
It's more important to save the layout than content of your terminal. After all why would you even bother restoring it if panes are named incorrectly? Think Mark! It's not about the text. It needs to looks good first. And rgiuegnuegne@#@#{$!!!

**Comment by FOSSilizedDaemon** [comment]
> I think this can be achieved by adding this line to the .tmux.conf
> `set -g @resurrect-capture-pane-contents 'on' # save pane contents`

That did it! Thank you :3
