### ISSUE TITLE
Creating new panes and overridden the windows name - After updates to the last version of tmux-resurrect 

### ISSUE THREAD

**Issue by ulises-castro** [tmux-plugins/tmux-resurrect#405]
Hi, it seems the last version breaks when we restore our session.

I creates automatically 5-10 new panes in each windows, and overridden  the windows names for "zsh"  (I am currently using oh my zsh).

I checked the last commits out from master, and it looks some changes are made to that functionalities, everything was working well until today.

I tried removing manually the new generated panes, but When I restore my session new panes are created again...

![image](https://user-images.githubusercontent.com/17864276/131390666-27f55f51-b6fe-4699-80f6-7cdbb162840b.png)

I have to downgrade and now it working well:
* To v3.0 of tmux-resurrect. (It does not work properly even with tmux 3.1)
* To 3.1 of tmux (It seems the  version 3.2a has several breaking changes).

**Comment by normen** [comment]
See #404
