### ISSUE TITLE
tmux source-file ~/.tmux.conf returned 127

### ISSUE THREAD

**Issue by ilteris** [tmux-plugins/tmux-resurrect#41]
Hi, I tried to install this as a plugin using the TPM unfortunately that didn't work. I tried manually afterwards, cloned it and put it under plugins dir, I added the line in the instructions. 

 run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux

Then run tmux source-file ~/.tmux.conf but get this back:

  '/Users/ilteris/.tmux/plugins/tmux-resurrect/resurrect.tmux' returned 127

currently,I couldn't make the plugin work for me.  I am on tmux 1.9a. I would love to make this work. 

You can check out my tmux.conf file here: https://github.com/ilteris/dotfiles/blob/master/tmux.conf

Thanks in advance.

**Comment by bruno-** [comment]
@ilteris, it's been a while we've talked about this, do you still have this issue?

**Comment by ilteris** [comment]
@bruno- So, it's still quite mystery. I gave up on it after our conversation. Then months later, I purchased a new laptop since we talked. I pretty much set it up, transferred my dotfiles and voila. Now I do have a working tmux-resurrect! I love it so much. 

However, it still doesn't work in the previous laptop. I guess we can close it.  Thanks a lot!

**Comment by bruno-** [comment]
Hi, thank you for providing feedback on this. Also, I'm glad things work for you now.

Yea, since it seems not a lot of other users are having this issue let's close it for now.
If anyone is experiencing this issue and is willing to spend some time investigating, please feel free to reopen and I'd be glad to help.

**Comment by ilteris** [comment]
Thanks @Bruno-!

**Comment by soosc** [comment]
If anyone else comes across the issue, this is what solved it for me.

Remove

```
run-shell ~/tmux-resurrect/resurrect.tmux
```

from `~/.tmux.conf` if installed via Tmux Plugin Manager. The above line is only needed when installing manually without the plugin manager.

**Comment by nick-bull** [comment]
Not specifically sure wht caused this for me, but deleting and reinstalling plugins didn't help. Instead just copied the file to where it wanted to be from Gtihub:

```
mkdir $HOME/.tmux/plugins/tmux-resurrect/scripts/ && curl -fsSL https://raw.githubusercontent.com/tmux-plugins/tmux-resurrect/master/scripts/restore.sh -o "$HOME/.tmux/plugins/tmux-resurrect/scripts/restore.sh"
```

**Comment by suikast42** [comment]
For me  with WSL2 this works:

`git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
~/.tmux/plugins/tpm/bin/install_plugins
`

**Comment by typesAreSpaces** [comment]
I had a similar issue; the following did it for me:
[https://git.2li.ch/tmux/tpm/commit/e51a3772b5e312900ea416740e14195df7cf4c22]()

I use a Mac laptop, so I included the address where Tmux is installed before any calls to `run-shell`
`set-environment -g PATH "/usr/local/bin:/bin:/usr/bin:/opt/homebrew/bin"`
