### ISSUE TITLE
Problems with the first panel of the first window

### ISSUE THREAD

**Issue by lfv89** [tmux-plugins/tmux-resurrect#42]
This plugin is awesome, and everything works perfectly fine, except for the first panel of the first window. 

When I save the session with ressurrect, execute `tmux detach`, execute `tmux new -s work` and then reload the environment using ressurrect, the first panel of the first window keeps the same state that my raw terminal had just after tmux was detached. All the other panels, on all the other windows work just fine.

My environment:

osx 10.9.3
terminal 2.4
tmux 1.9

Let me know if you need anything any more information about this issue.

**Comment by bruno-** [comment]
Hmm.. I'm not sure if that would be possible. But anyway, I think there's a workaround when you forget to rename the first session.

So, you just started tmux, you're in a session named (by default) `0` with 1 window. You want to do the restore now, but that first window won't be restored. So get around the issue, you can \*now* rename the default session `0` to, let's say `foobar` and do the restore. Session `0` will be created from scratch including the first window.

Let me know if that helps.

> What about an option to blow away the existing session and just restore the old one?

Yea, I should probably enable this somehow, as more people is having issues with this. I'll let you know here when it's done.
