### ISSUE TITLE
Can I restore tmux session outside tmux?

### ISSUE THREAD

**Issue by CengsBlanky** [tmux-plugins/tmux-resurrect#420]
Is there a way that I can just open previous saved session outside tmux? 

Something like `tmux attach-session -f [tmux_resurrect filename]`, so I do not need to open two sessions and one of them is useless.

Or can I write a script to use resurrect's functions to achieve that.
I'm just curious, that would be more convenient.

**Comment by scmanjarrez** [comment]
I have this in my startup scripts.
```
#!/bin/bash                                                                                                                                                   
                                                                                                                                                              
echo "Starting tmux..."                                                                                                                                       
                                                                                                                                                              
# check if tmux session exist, create a new session if not                                                                                                    
tmux ls > /dev/null 2>&1                                                                                                                                      
if [ $? -eq 1 ]; then                                                                                                                                         
    tmux new -d                                                                                                                                               
    # attach drop-down terminal to tmux                                                                                                                       
    xfce4-terminal --drop-down --title "tmux" -e "tmux attach" --tab -e "tmux run ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh"                          
else                                                                                                                                                          
    xfce4-terminal --drop-down --title "tmux" -e "tmux attach"                                                                                                
fi 
```
I create two separate tabs (1 is removed after loading session), 1 is needed to create a tty for tmux and the other one restore your last session. Opening only 1 tab without attaching before won't restore your last window (the one marked with a star \*).
I use it for xfce, but you can modify it for whatever terminal.

**Comment by CengsBlanky** [comment]
> I have this in my startup scripts.
> 
> ```
> #!/bin/bash                                                                                                                                                   
>                                                                                                                                                               
> echo "Starting tmux..."                                                                                                                                       
>                                                                                                                                                               
> # check if tmux session exist, create a new session if not                                                                                                    
> tmux ls > /dev/null 2>&1                                                                                                                                      
> if [ $? -eq 1 ]; then                                                                                                                                         
>     tmux new -d                                                                                                                                               
>     # attach drop-down terminal to tmux                                                                                                                       
>     xfce4-terminal --drop-down --title "tmux" -e "tmux attach" --tab -e "tmux run ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh"                          
> else                                                                                                                                                          
>     xfce4-terminal --drop-down --title "tmux" -e "tmux attach"                                                                                                
> fi 
> ```
> 
> I create two separate tabs (1 is removed after loading session), 1 is needed to create a tty for tmux and the other one restore your last session. Opening only 1 tab without attaching before won't restore your last window (the one marked with a star *). I use it for xfce, but you can modify it for whatever terminal.

Thanks, this is helpful!!!
