### ISSUE TITLE
How to Not Display Message When Restoring?

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [tmux-plugins/tmux-resurrect#425]
Whenever `save.sh` is run the statusbar is flashed with a message saying that it is saving the environment. What variable do I set to disable this?

**Comment by Hologos** [comment]
According to this

https://github.com/tmux-plugins/tmux-resurrect/blob/6050d2d8d8a9052c6a30e88fa27e6d5e3844e52a/scripts/save.sh#L262-L277

You have to change this line https://github.com/tmux-plugins/tmux-resurrect/blob/6050d2d8d8a9052c6a30e88fa27e6d5e3844e52a/resurrect.tmux#L12

```bash
tmux bind-key "$key" run-shell "$CURRENT_DIR/scripts/save.sh quiet"
```

Then you have to reload the configuration.

**Comment by FOSSilizedDaemon** [comment]
Perfect! Thank you!

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------
