### ISSUE TITLE
Only Save Session Name If It Matches a Specific Session Name?

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [tmux-plugins/tmux-resurrect#426]
I have an annoying issue where sometimes, by accident, I will spawn a new tmux session that I do not intend to save. I was curious if it would be possible to add in a condition to not save if a session name does not match a set one? Something like the following in main (within resurrect.tmux)
```
if [ "${current_session_name}" = "${target_session_name}" ]; then
    set_save_bindings
    set_restore_bindings
    set_default_strategies
    set_script_path_options
fi
...
```
I am unsure how GitHub works, but I could implement this myself. This would also have to be done in `save.sh`.

**Comment by FOSSilizedDaemon** [comment]
I wrote a solution: https://gitlab.com/FOSSilized_Daemon/dotfiles/-/blob/main/src/dotfiles/home/.program/non-privileged/cli-misc/trts/trts

**Comment by bruno-** [comment]
Also check out this plugin that works with `tmux-resurrect`: https://github.com/spywhere/tmux-named-snapshot

It allows saving/restoring individual sessions.
