### ISSUE TITLE
Session does not Restore

### ISSUE THREAD

**Issue by Jarrod-RDS** [tmux-plugins/tmux-resurrect#429]
This is likely an O.E. (Operator Error) on my part. I followed directions, looked in Issues, even is:closed issues but could not find answer or figure out what I may be doing wrong.

I have tpm installed via the git clone method to ~/.tmux/plugins/tpm
In ~/.tmux.conf I have:
```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.tmux/plugins/tpm/tpm'
```

I have sourced this file:
tmux source ~/.tmux.conf

I setup a tmux session, multiple panes, one running top, others tailing log files, with a large "work area" pane.
I use the default "prefix" for tmux commands, which is Ctrl b
I hit Ctrl b then Ctrl s to save session. No message is shown
I close terminal that tmux is running in, without exiting tmux. I am shown  warning about tmux running but close anyway. this is to simulate a an unclean exit similar to what might happen during a power failure
I open new terminal, type 'tmux' and once in tmux I hit Ctrl b Ctrl r but the session is not restored.

I am testing this out on my Linux desktop (debian) before trying this on any servers.

**Comment by nbn22385** [comment]
Have you installed the plugin(s) with `<prefix>I` or run `~/.tmux/plugins/tpm/bin/install_plugins`?

**Comment by Jarrod-RDS** [comment]
That was it, thank you.

Once I Crtl b then I, I was able to save session and restore it later
