### ISSUE TITLE
Save / Restore a named snapshot

### ISSUE THREAD

**Issue by spywhere** [tmux-plugins/tmux-resurrect#436]
> _I've tried look into the open/closed issues for something similar but none was found, so here's my request on it._

### Request
Is there anyway to save and restore a named snapshot?

### Rationale
I have both tmux-resurrect and tmux-continuum installed. While I'm happy with the setup with both plugins, I'm in a lack of control over the save/restore behavior.

I would like to have tmux-continuum as my backup resort to restore my tmux session while I still be able to just "take a snapshot" and not get override by tmux-continuum on the next interval.

With tmux-continuum constantly saving the session, I can be sure that my snapshot will not get lost when unexpect event occurred (e.g. power loss). And I can also control when to restore my snapshot, even after the first save interval.

#### Minimum Expectation

Introduced a new variable (e.g. `@resurrect-manual-snapshot-name`) and two new key bindings to save and restore this named snapshot.

#### Desired Expectation

Introduced two new variables (e.g. `@resurrect-manual-save` and `@resurrect-manual-restore`) which take the format of...

```
[key]->[name] [key]->[name]...
```

similar to how `@resurrect-processes` get set currently.

- `key` would be a keybinding to save/restore `name` snapshot
- `name` would be a snapshot name to save as

Should the name contain space, a double quote can be put in place as well (as suggested, similar to how `@resurrect-processes` works). So it could be `"C-w->web dev" "C-d->web deploy" C-l->logs`, which will setup 3 keybindings for save/restore 3 named snapshots separately.

---

This `name` will be used in the snapshot file name. So instead of using default `${RESURRECT_FILE_PREFIX}_${timestamp}.${RESURRECT_FILE_EXTENSION}`, the named snapshot will be `${SNAPSHOT_NAME}.${RESURRECT_FILE_EXTENSION}`

PS. I'm fine in open a pull request for this feature, might as well start a fork on it sometime soon

**Comment by spywhere** [comment]
Hi Bruno, thank you for your response and suggestions. This definitely sounds like a good plan to me. I'll close the ticket.

Once I done the first iteration of the plugin, I will probably put it up here in case someone might need something similar.

**Comment by bruno-** [comment]
Sure, once you have it working you can submit it to the [plugins list](https://github.com/tmux-plugins/list) if you want people to find it out.

**Comment by spywhere** [comment]
For those arrived here, [check out the plugin here](https://github.com/spywhere/tmux-named-snapshot).

**Comment by me-nkr** [comment]
I see there is already a solution but, I have just made one with a simple interface. check it out here https://github.com/me-nkr/dotfiles/tree/main/utils/tmux
