### ISSUE TITLE
Panes not "clean" on restore

### ISSUE THREAD

**Issue by barrett-ruth** [tmux-plugins/tmux-resurrect#452]
So, tmux-resurrect works. I currently have ressurect set up and it correctly preserves pane contents. However, I notice that when I save a session and restore tmux, the panes are all "scrolled up."

As in, when I type several commands, clear the pane with <c-l>, save, and then restore, the pane's full history of those several commands is in view (rather than an empty pane as I saved it). Is there any way to alter this behavior?

**Comment by simoncarrignon** [comment]
Have the same issue: after restoring all windows and pane,  panes are simply piled one on top of the other.  @barrett-ruth branch indeed solved it for me!

**Comment by barrett-ruth** [comment]
see #452
