### ISSUE TITLE
Start window commands lazily after restore

### ISSUE THREAD

**Issue by paddor** [tmux-plugins/tmux-resurrect#465]
Feature suggestion: Start window commands lazily after a restore. This could speed up restoring (takes about 10s for me) and would also improve convenience of refreshing shells that lookup stuff while they're being initialized (thinking of chruby's list of available Rubies).

**Comment by alchemmist** [comment]
@paddor, right now I use a new tool, that completely solve this problem for me. This can save all sessions setup with running process and scrollback history and restore it lazy only when you first time go to some sessions.

Maybe, it will be useful for you too:
https://lazy-tmux.xyz/
