### ISSUE TITLE
Arrow (->) substitution preserving arguments

### ISSUE THREAD

**Issue by ktprograms** [tmux-plugins/tmux-resurrect#468]
I use MacVim, so my vim processes are `/opt/homebrew/Cellar/macvim/.../MacOS/Vim`, which means that I need to use `~vim->vim` in my `ressurect-processes`. The problem with this is that the files I was editing don't get restored (the process ends up as just `vim`, when I'd want something like `vim main.go`).

If there was a way I could match and replace on _only_ the first argument (even regex would be fine), that'd be great!

**Comment by bruno-** [comment]
Try `"~vim->vim *"`

**Comment by ktprograms** [comment]
Thanks, I found that from looking at the code. I'll submit a PR to add it to the docs.

However, there's a small bug. When just `vim` is used without any arguments, in [`_get_command_arguments()`](https://github.com/tmux-plugins/tmux-resurrect/blob/027960a/scripts/process_restore_helpers.sh#L124), `$pane_full_command` is `vim` and `$match` is `vim`, but because the regex needs a trailling space, the match is not removed, and `vim vim` gets executed.
