### ISSUE TITLE
tmux crashes upon startup if resurrect plugin is enabled

### ISSUE THREAD

**Issue by kushalj1997** [tmux-plugins/tmux-resurrect#475]
Seems to only happen on one linux desktop, adding tmux resurrect to the plugins list causes a crash of tmux upon startup, how do I debug this?

**Comment by mvaldes14** [comment]
have the same issue, for some reason it started to blow up recently.
if i disable the plugin everything works perfectly.

happy to provide some logs if someone knows how to get them.

**Comment by mvaldes14** [comment]
Fixed mine by overriding the resurrect file location as the documentation indicate; It now lives in tmp, will persist it somewhere else but for now it will do.

**Comment by kushalj1997** [comment]
@mvaldes14 do you mind dropping a link / snippet to where I can change this? THanks!

**Comment by mvaldes14** [comment]
always RTFM - https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/save_dir.md

**Comment by kushalj1997** [comment]
Useful to have all the information in one thread for others that come by! Set mine to `/home/$USER/.tmux/resurrect-dir` with good success. Use `CTRL+B + CTRL+S` first time around to save your tmux environment, and then exit and reopen tmux, continuum-restore brings it back for me correctly.
