### ISSUE TITLE
Resurrect not saving the tmux session as intended

### ISSUE THREAD

**Issue by IsabellaSampaio** [tmux-plugins/tmux-resurrect#493]
I'm getting this problem where my tmux command `prefix C-s` and `prefix C-r ` are not working as expected, they aren't saving neither restoring my session. I've looked around the issues list trying to find a solution to this problem but nothing has worked. Also looked into some subreddits but it didn't help much either. I'm currently running tmux 3.2a and the most recent Pop os version. Here's my current `tmux.conf` file:

```
# config to change the default ctrl b bind 
unbind C-b
set -g prefix C-Space 
bind C-Space send-prefix

# shift alt keys from vim
bind -n M-H previous-window
bind -n M-L next-window

# setting the plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'

```

**Comment by karsov** [comment]
I was having the same issue and it turned out that I forgot to actually install the Tmux Plugin Manager.
Please, check that the steps in "Installation" and "Installing plugins" from the plugin manager readme are done:
https://github.com/tmux-plugins/tpm

**Comment by IsabellaSampaio** [comment]
> I was having the same issue and it turned out that I forgot to actually install the Tmux Plugin Manager. Please, check that the steps in "Installation" and "Installing plugins" from the plugin manager readme are done: https://github.com/tmux-plugins/tpm

That solved my problem, thanks :)
