### ISSUE TITLE
pane directories not restored

### ISSUE THREAD

**Issue by jmlucjav** [tmux-plugins/tmux-resurrect#50]
Hi

I am starting to use this great plugin. I have created a session, but when I restore it, my panes are not in the dirs I left them at. I didn't find anything in the readme about this, do I need to do something special?

thanks

**Comment by soyuka** [comment]
Hi,

First, I love your work on tmux plugins, I use a lot of them :); thanks!

I'm expecting this issue as well.

My `~/.tmux/resurrect/last` looks fine according to the previous one. I'm always working in named sessions.

For information, I tried to manually `split-window` (same behavior with new-window):
```
#this doesn't work
❯ tmux split-window -c "~/sites/ds"
bad working directory: No such file or directory
#this does
❯ tmux split-window -c ~/sites/ds
```

I start tmux this way: `urxvt -e tmux -2` and then <Prefix+C-r> but everything goes to the `pwd` while sending  <C-r>.

**Comment by soyuka** [comment]
I had the `last-working-dir` plugin in my zshrc, it was breaking tmux restore. 

I removed it and restore went smoothly. For me it's fixed.

**Comment by bruno-** [comment]
Thank you for letting us know how you fixed this. This could be useful for other people having the same problems.

**Comment by soyuka** [comment]
By disabling `last-working-dir` I've lost the feature, here is my alternative.

```
# window splitting
unbind %
bind | split-window -h -c '#{pane_current_path}' 
unbind '"'
bind _ split-window -v -c '#{pane_current_path}'
```

When opening a new pane, this will create it with the pwd of your previous active pane.

[Source](http://unix.stackexchange.com/questions/146825/tmux-new-pane-has-home-directory-as-default-instead-of-previous-directory)

**Comment by jmlucjav** [comment]
I cannot reproduce this now, tried in two hosts and works always.

**Comment by bruno-** [comment]
This issue was reported to tmux core as issue 155. Since tmux repository moved to github, the discussion at the core mailing list is now lost.

Since other users still seem to have this issue here's the gist of the discussion at tmux core mailing list:

1. Try `tmux new-window -c '/tmp'`. If this \*does not* open a new window in `/tmp` something is wrong, see next step.
2. Try `tmux new-window -c '/tmp' 'pwd; sleep 1000'`. It should show `/tmp` directory on the screen. If yes, then tmux is ok and a user config (eg bashrc, zsh plugins, something else) is wrong.

**Comment by desnudopenguino** [comment]
I'm having the same issue, but I'm running OpenBSD with ksh as my shell. Could that be part of the issue? I have a nearly empty .profile so it shouldn't be anything with the user config, but it might be...

**Comment by spazione** [comment]
Same problem, but I'm running Ubuntu 14.04 with bash

**Comment by spazione** [comment]
If I check my `~/.tmux/resurrect/last` after the reboot and before that I try to attach it to any session, everything it seems ok (paths & programs). But after `tmux attach-session -t sessionName` tmux looses the paths and after that tmux-continuum rewrite the sessions, all paths are lost
