### ISSUE TITLE
Failed to resurrect first panel?

### ISSUE THREAD

**Issue by zhangyuting** [tmux-plugins/tmux-resurrect#53]
Firstly, thanks for your effort on this good plugin. I have tested several times, I found that the first panel I created always failed to resurrect. I have checked the saved file, I see the directory and vim file are all looks good. But the first panel always just use the default directory and do not resurrect my vim session, at the same time, other panels are all works well, do you have any idea? thanks.

**Comment by bruno-** [comment]
Hi guys,
I just want to let you know this "issue" has been addressed in the latest version of `tmux-resurrect`.

The plugin will now restore the first pane by effectively overwriting it. This overwrite will happen only if the **first pane is the only pane for the whole tmux server**. It is assumed a user wants to restore previous environment "from scratch" so this overwrite should be safe.
