### ISSUE TITLE
Window names are no longer dynamic after restore

### ISSUE THREAD

**Issue by frontierpsycho** [tmux-plugins/tmux-resurrect#57]
I started using tmux-resurrect recently, and I really like it, but I seem to have a problem with window names.

Before I started using tmux-resurrect, window names would be updated based what was running in them at the time. When working on a resurrected session, however, the names of the resurrected windows never change: If I run vim on one of them, the name is still bash. If I quit vim on one that was already called vim (because it was running vim when I saved the session), its name keeps being vim.

**Comment by rootulp** [comment]
Created a [workaround](https://gist.github.com/rootulp/93f67511ae97c20c4d32b600a5ab6a8d) to enable `automatic-rename` on all tmux windows

**Comment by mayanksuman** [comment]
Submitted a pull request #222 that fix this bug.
