### ISSUE TITLE
Can't restore the session with base-index is 1

### ISSUE THREAD

**Issue by nhtvinh** [tmux-plugins/tmux-resurrect#63]
Hi Bruno,
 I found that with tmux config base-index is 1, after I saved the session, the restoring process can't restore the first window of the session. These are my .tmux.conf and last files. 
https://gist.github.com/nhtvinh/8f81cc934960bd482872

Please help check.

Best regards,
Vinh Nguyen.

**Comment by bruno-** [comment]
Hey Vinh,
sorry for the late answer. I think you might be having a common issue that is explained in the [FAQ](https://github.com/tmux-plugins/tmux-resurrect#faq).

As FAQ and the link explain, the solution is simply to name your sessions (the binding for that is `prefix + $`). Hope that helps.

There's been quite some open issues for `tmux-plugins` during the holidays so I'm trying to close them as much as possible. I think the above will explain and fix your problem, so I'll close this issue. Please, feel free to reopen if things dont work or you still have questions.

**Comment by nhtvinh** [comment]
Hi Bruno,

Thank for your response. I did check the solution and it worked well.

Best regards,
Vinh Nguyen.
