### ISSUE TITLE
Can this be cron'ed?

### ISSUE THREAD

**Issue by isthisthat** [tmux-plugins/tmux-resurrect#68]
Is it enough to add `~/.tmux/plugins/tmux-resurrect/scripts/save.sh` to my crontab or will this not work outside of tmux?
Thanks a lot for this great plugin!

**Comment by markeissler** [comment]
Yes, but also no. Right now it would be pretty intrusive to have what you're doing be interrupted by the backup process. It was never meant to be run automatically. What you are more than likely interested in is this:

[Proposal for auto-save #35](https://github.com/tmux-plugins/tmux-resurrect/issues/35)

I've started work on that issue. For more info, see the link.

**Comment by isthisthat** [comment]
Excellent! Thanks Mark.

**Comment by bruno-** [comment]
Hey,
there's now a plugin for automatic/continuous saving of tmux environment [tmux-resurrect-auto](https://github.com/tmux-plugins/tmux-resurrect-auto).
I'd appreciate if you tried it out and reported if everything works okay.

Other than that, I think that plugin should replace the functionality from this issue so I'm closing it.
