### ISSUE TITLE
question: does it support named session?

### ISSUE THREAD

**Issue by stephencheng** [tmux-plugins/tmux-resurrect#69]
I understand that I can use bind key to save and later to restore that saved session, but how can I create different named session? eg, when I work with session 1 - named: project1_session, then I save the session using prefix+ctrl-s, and later on I hit prefix+ctr-r to restore project1_session. It seems I can only save one session by default and it overwrites previous saved session and when restoring for session, it can only restore from last saved. 

What about I need to save multiple projects? Is it possible? or I missed anything?

**Comment by soyuka** [comment]
I'm using multiple sessions and tmux-resurrect is restoring every named session. It might be necessary to have a `0` session with nothing in it (correct me if I'm wrong).
Make sure you named your sessions:
```
prefix+: new-session -s name
#or
prefix+: rename-session name #will rename the current session or choose a target -t 
```
Just tried again and it's restoring my sessions just fine :).

**Comment by stephencheng** [comment]
Thanks.  It did work, however it loads up all the saved sessions in one go.

It's not clearly said if I can only load up one of the saved/hibernated session but not all of them. Possible? and how?

**Comment by bruno-** [comment]
Hey, yea, saving and restoring multiple sessions should work without problems. That's the core feature.

> but how can I create different named session?

If you have troubles creating new named sessions, you might want to look into [tmux-sessionist](https://github.com/tmux-plugins/tmux-sessionist) that gives you `prefix + C` to do just that (among other things).

> It's not clearly said if I can only load up one of the saved/hibernated session but not all of them. Possible?

I see what you mean, but this is not possible.

**Comment by stephencheng** [comment]
Thanks. Also, how can I remove/delete the saved sessions if I don't need them any more, I found all of them will come back to life though I don't want it that way.

**Comment by markeissler** [comment]
Hrmm. I guess most of us have been concerned with resurrecting the same sessions. I'm working with the files in .tmux/resurrect right now anyway so maybe I'll just put a note in my queue to write a script that will purge old (unwanted) sessions?

**Comment by soyuka** [comment]
`tmux kill-session` and save again ?

**Comment by stephencheng** [comment]
ok, I finally got the idea, the save operation is to all sessions, it's not a per session based. Thanks to soyuka for hitting the point.
