### ISSUE TITLE
Add option to overwrite existing session

### ISSUE THREAD

**Issue by jwhitley** [tmux-plugins/tmux-resurrect#70]
In [this comment](https://github.com/tmux-plugins/tmux-resurrect/issues/35#issuecomment-67714214) in #35, a rationale is presented for not altering an existing window:

> There is an explanation and solution for the "not restoring first window" problem, it's because restore shouldn't clobber an already-open window.

I have a concrete use case that goes exactly the other way.  First, I never use a tmux session named `0`.  I have a [tmux front-end script](https://github.com/jwhitley/tilde-local/blob/master/local/bin/mux) which I always use to start and/or restore named sessions.  It's got [zsh auto-completion](https://github.com/jwhitley/zshrc/blob/master/.zfunctions/_mux), and when my usual shortcut opens a new iTerm2 window I go so far as to display existing sessions and put up an auto-completing prompt to open a new or existing tmux session.  tl;dr: I put up a high wall of convenience around ever using session `0`.

In these sessions, 99% of the time the first pane in the first window is a vim instance.  I.e. where all of my actual work is happening.

As such, the current behavior restores the session but *fails* to restore the most important pane in that session.  I'm left with a useless default shell pane, instead of the pane I really wanted.

Thus I would be highly interested in an option that overwrites the existing session.  It probably makes sense to guard this functionality so that an overwrite will only occur if there's a single pane in a single window -- this is likely to be a default pane anyhow, and it limits potential damage from accidentally restoring to a established session.

**Comment by bruno-** [comment]
Hi @jwhitley, thanks for getting involved.

You've got an interesting workflow. I checked your script - do you know how many other people are using it?

I was thinking of addressing this general "overwrite" pane issue new users are having.

Can you please tell me would the following implementation be ok for your workflow:
- a user starts tmux and invokes the process for restoring 
- if this newly started tmux instance has \*only 1 session with only 1 pane in it*, that probably means a user is doing a restore from scratch. Overwrite that single tmux pane and of course restore other panes and sessions as well.
- if the newly started tmux instance already has multiple sessions or a single session has multiple panes, that probably means a user a user has done some active work already. Do \*not* override any panes.

**Comment by markeissler** [comment]
@bruno I'd hold off on this for now. I've got a feature branch brewing that will address auto save, and long with that, auto restore. It will also address the "not restoring first window" problem that I understand the reasoning behind, but for me it's an annoyance.

I also have a wrapper script (that I've been using all along) that provides me with three options:

```sh
Available TMUX sessions
-----------------------

1) _default
2) NEW SESSION
3) BASH
Please choose your session:
```
The _default sessions is always available as an option. Additional named sessions would appear beneath it. I plan on adding a script like this to tmux-resurrect. It will also list previous named sessions that can be restored. Therefore, when a user starts tmux (from the wrapper) they will get the opportunity to restore a session, in which case it will restore all panes, including the very first one.

Anyway, this feature branch will be ready within a week (I predict). It addresses other things too, like purging old resurrect files automatically. And also, of course, implements auto-save, the feature so many of us have wanted. And includes history and buffer save/restore for BASH. I will work on ZSH next.

**Comment by bruno-** [comment]
Hey @markeissler ,
thanks for all the work on this. But, I'm not sure if submitting one giant pull request with ton of features would be the best approach for getting it merged. [Others have written about this](https://www.igvita.com/2011/12/19/dont-push-your-pull-requests/).

I'd sure appreciate if you could make a pull request that handles "not restoring first window" issue only.

I'm also not sure about merging other features to tmux-resurrect. I'd like encourage you to work on them as separate plugins, extensions to tmux-resurrect.
If you want I'll create a separate repo in `tmux-plugins` github org where you can work on this.
When they are done, I'd be glad to link to those projects from the tmux-resurrect readme page. I hope this is okay with you.

**Comment by jwhitley** [comment]
@bruno-, the flow proposed in your first comment sounds spot on for what I was thinking. It's a nice compromise between workflow and safety. 

I don't know how many folks are using my script, but it's effectively a super fancy version of a common tmux alias:

`alias tn="tmux new-session -ADs"`

I've used some form of this since screen, before tmux existed.  Once you have this, it becomes quite normal to create "topic" sessions as needed.

**Comment by markeissler** [comment]
Hey @bruno, I understand your concerns. I think rather than polluting this ticket with an off-topic conversation, I'll contact you directly.

For anyone else interested in my work-in-progress on the new auto save functionality, my ongoing work is on this feature branch of my fork:

https://github.com/markeissler/tmux-resurrect/tree/feature/save-auto

**Comment by bruno-** [comment]
Hey @markeissler, sorry I see this just now. My inbox is swamped.

@jwhitley thank you for the feedback.
This feature is now implemented in `first_pane_overwrite` branch.
It should work, but I'd like to give it some more time for local testing, before merging to `master` branch. If you wanna test it, feel free to provide feedback.

**Comment by bruno-** [comment]
The feature described in [this post](https://github.com/tmux-plugins/tmux-resurrect/issues/70#issuecomment-72201880) is implemented and merged into master.

That should handle the core reason why this issue is opened, so I think it's safe to close it now.
