### ISSUE TITLE
Can't have vim ressurected anymore

### ISSUE THREAD

**Issue by MoOx** [tmux-plugins/tmux-resurrect#72]
Hi,

First of all, thanks for all your plugins.

When I first try tmux + tmux ressurect, vim sessions were restored, but I don't know how or when it start to fails. Vim just doesn't restart. If I save a session (I use tope/vim-obsession), kill tmux and restart/restore, vim just doesn't start again :/

Here is my tmux conf https://github.com/MoOx/setup/blob/master/dotfiles/tmux.conf

Here is my tmux/last

```
pane	tmoox	1	:vim	1	:*	0	:/Users/MoOx/setup	1	vim	:-zsh
pane	tmoox	1	:vim	1	:*	1	:/Users/MoOx/setup	0	zsh	:-zsh
window	tmoox	1	1	:*	f0c1,203x59,0,0{101x59,0,0,1,101x59,102,0,2}
state	tmoox	tmoox
```

tmoox is just `alias tmoox="tmux attach -t tmoox || tmux new -s tmoox"`

Can this be related to a vim plugin or something like that ?

I am using iTerm 2 latest build on OS X 10.10, here are some other informations:

```console
$ tmux -V
tmux 1.9a

~
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 16 2015 10:08:54)
MacOS X (unix) version
Included patches: 1-488
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc
```

**Comment by bruno-** [comment]
Hmm.. your config looks okay.

Can we first rule out the option this is not related to vim? So can you please try this:
- open vim and edit a couple files (just to have something)
- make sure session tracking with `vim-obsession` is turned on
- quit vim
- does the current directory have `Session.vim` file? This is the file where vim's session is stored.
- try restoring the previous session with ` vim -S`. Did this work as expected?

I also see you're trying out `tmux-resurrect-auto`. Thank you for being "early" adopter, please also let me know if you encounter any hiccups with that.

**Comment by MoOx** [comment]
I already try these steps and they are working fine. Session.vim ok, vim -S restoring session ok.
I just added `auto` this morning, but I were getting the issue before adding it.

**Comment by bruno-** [comment]
Okay, thank you for the quick feedback.
I just re-read your first post:

> but I don't know how or when it start to fails. Vim just doesn't restart.

Does this mean vim does not start for you \*at all*? Or vim starts but vim's session is not restored?

**Comment by MoOx** [comment]
Vim do not restart at all. Cwd is ok, but ressurect do not start vim again.

**Comment by bruno-** [comment]
Hi,
I can reproduce the problem with the `last` file you provided.

The issue seems to be that for the first pane (first row in the file), vim is not detected as a running program (see screenshot).

![screen shot 2015-02-16 at 2 12 57 pm](https://cloud.githubusercontent.com/assets/1042682/6212477/16877dd0-b5e6-11e4-84fa-b18e811f91eb.png)

Not sure why this happens because in the field to the left (that is tmux native program detection), vim is detected, but that field is not used for restore bc it's very imprecise.

The first assumption I'd make is that somehow you're running another `zsh` program instance within the original tmux pane. So a scenario like this:

- zsh process (the first process in tmux pane)
- another zsh process (this is what `tmux-resurrect` detects)
- vim

Does this maybe ring any bell for you? It's just a vague assumption though..
Also, how do you run vim? Do you have any kind of helper script or shell function that does that?

This is just an update, I'll continue investigating.

**Comment by MoOx** [comment]
The thing is I run tmux through iTerm 2 which run zsh, and tmux run zsh too, so maybe I got a zshception somehow.

I run vim via "vim" or "vim -S", nothing more. I probably think the issue came from the problem above.

**Comment by MoOx** [comment]
Maybe it's related to iTerm2, I will take a look.

**Comment by MoOx** [comment]
Can it be related to something like this?

![screen shot 2015-02-16 at 14 59 12](https://cloud.githubusercontent.com/assets/157534/6213081/68165cec-b5ec-11e4-8145-9e23deed9ecd.png)

I've to admit I never really understand the idea behing "login shell" and friends.

What is the recommanded setup to get a terminal that always start a unique tmux session ?

**Comment by bruno-** [comment]
I think I got it! This line from your `tmux.conf` seems to be making problems:

    set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

Here's how I tested locally (btw. I used `bash` but I don't think that plays a role here).

Scenario 1, vim is \*not restored*:

    set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l bash"

Scenario 2, vim \*is restored*:

    set-option -g default-command "reattach-to-user-namespace -l bash"

I think this makes sense with how things are saved in the `last` file. For scenario 1, these are the running processes:

- which reattach-to-user-namespace (the first process in tmux pane)
- reattach-to-user-namespace -l $SHELL (this is what `tmux-resurrect` detects)
- vim (this is \*not* detected)

Can you please let me know does changing the `default-command` fix the issue?

**Comment by bruno-** [comment]
Also, if this does the trick, maybe we can make a change to `tmux-sensible` so that you don't even have to set this option in `tmux.conf`?

**Comment by MoOx** [comment]
Using 

```
set-option -g default-command "reattach-to-user-namespace -l $SHELL"
```

 helps a lot.

I think I used the `which ...` trick for when you are not in iTerm or... Can't really remember if this make sense.

Anyway thanks for investigating!

I not comfortable with terminal enough to tell you if you should add the reattach thing to tmux-sensible or not. FYI, I am not a sys admin or something, just a frontend dev who does css and js ^^). It's up to you to decide. Just note that on OS X for example, reattach-... command is not included by default and need a brew install :)

I found the long command that contain `which` trick here https://github.com/atom/atom/issues/3093#issuecomment-59784274

**Comment by bruno-** [comment]
Okay, great. Wanna close the issue if this now works for you?

About adding `reattach-to-user-namespace` to `tmux-sensible` - that is already added with proper checks [link](reattach-to-user-namespace).

I thought there is a specific reason why you override that in `tmux.conf` while using `tmux-sensible`. If no, then I think it's safe to recommend to completely remove setting `default-command` in `tmux.conf`.

**Comment by MoOx** [comment]
I will double check my conf & tmux-sensible. Thanks for all of this. Have a nice day :)

**Comment by olbrew** [comment]
I'm having the exact same problem so opening a new bug doesn't seem necessary.
`tmux-ressurect` restores my sessions, windows, ... just fine but it doesn't even restart vim.
I have set the necessary options in .tmux.conf (along with the `reattach-to-user-namespace` option) , there is a `.session.vim` file (custom filename, changed accordingly in the code) present and when called manually it restores vim just fine.
I'm using fish shell as my default shell but have set bash as the login shell. I use fish through iTerm2 which automatically executes it on startup.

I was trying to fix it myself but I can't find where it actually calls the `vim_session.sh` script in the restore strategy.

@bruno- could you help me alone?

**Comment by bruno-** [comment]
Hey @olbrew, can you link the content of `~/.tmux/resurrect/last` file.

I suggest trying with vim's default `Session.vim` as this plugin does not support using custom session file names (eg `.session.vim`).

`vim_session.sh` is called from [here](https://github.com/tmux-plugins/tmux-resurrect/blob/ed6fb9b5239a7112e9daf82234a237994dc219a6/scripts/process_restore_helpers.sh#L30-L32).

**Comment by olbrew** [comment]
I had manually changed the vim session files to point to my hidden files in `vim_session.sh` .
I still tried with the normal Session.vim file but it also doesn't work.

Thank you for the execution location. I was trying to see if the vim restore script actually executes by placing echo statements in it. So far I haven't seen the results. Will try further when I have some time.

Here you have my ressurect file (I changed the directories to "Dir"):
```
pane	0	0	:fish	1	:*	0	:Dir	1	fish	:-fish
pane	ai	0	:fish	1	:*	0	:Dir 1	fish	:-fish
pane	ds	0	:ds	1	:*	0	:Dir 0	fish	:-fish
pane	ds	0	:ds	1	:*	1	:Dir 1	vim	:-fish
pane	ew	0	:fish	1	:*	0	:Dir	0	fish	:-fish
pane	ew	0	:fish	1	:*	1	:Dir	1	fish	:-fish
pane	ew	0	:fish	1	:*	2	:Dir	0	fish	:-fish
pane	ew	0	:fish	1	:*	3	:Dir	0	fish	:-fish
pane	main	0	:	1	:*	0	:Dir	1	fish	:-fish
pane	main	0	:	1	:*	1	:Dir	0	fish	:-fish
pane	tc	0	:vim	1	:*	0	:Dir	0	fish	:-fish
pane	tc	0	:vim	1	:*	1	:Dir 	0	fish	:-fish
pane	tc	0	:vim	1	:*	2	:Dir	1	fish	:-fish
pane	tc	0	:vim	1	:*	3	:Dir	0	fish	:-fish
window	0	0	1	:*	b69e,204x52,0,0,1
window	ai	0	1	:*	b69f,204x52,0,0,2
window	ds	0	1	:*	6151,204x52,0,0{101x52,0,0,3,102x52,102,0,4}
window	ew	0	1	:*	8247,204x52,0,0{68x52,0,0[68x25,0,0,5,68x26,0,26,6],67x52,69,0,7,67x52,137,0,8}
window	main	0	1	:*	7101,204x52,0,0{101x52,0,0,9,102x52,102,0,10}
window	tc	0	1	:*	cb77,204x52,0,0[205x25,0,0{101x25,0,0,11,103x25,102,0,12},205x27,0,26{101x27,0,26,13,103x27,102,26,14}]
state	ds
```

Thank you!

**Comment by bruno-** [comment]
Hey,
based on the `last` file content you provided maybe there's something wrong with your setup.

![screen shot 2015-11-02 at 11 08 48 pm](https://cloud.githubusercontent.com/assets/1042682/10895902/f27d79c4-81b6-11e5-828a-d4f9a56baff6.png)

What's the output of `tmux show -g default-command`?

**Comment by olbrew** [comment]
default-command "reattach-to-user-namespace -l fish"

Hmm so it could definitely have something to do with the fish shell. I did try the restore on a bash shell where it didn't work either, but saved the above file on the fish-shell.

**Comment by bruno-** [comment]
Hmm, your `default-command` looks ok. Not sure what's causing this..

**Comment by mk12** [comment]
I found a solution to this:

```
set -g default-shell /bin/bash
set -g default-command "reattach-to-user-namespace -l /usr/local/bin/fish"
```

For some reason reattach-to-user-namespace doesn't work properly when you run it in fish. However, it's no problem to run it in bash instead since you're creating a new fish shell anyway.

**Comment by neowulf33** [comment]
Thanks. That worked - we need these instructions in the wiki!
