### ISSUE TITLE
[feat] Reset time (prefix + t)

### ISSUE THREAD

**Issue by soyuka** [tmux-plugins/tmux-resurrect#76]
It's really no big deal but it could be nice if the time could be resurrected :).

**Comment by bruno-** [comment]
Ha, okay - user asked for it :)
I'd be willing to accept a PR for this if someone want's to do it and it doesn't add complexity to the code.

**Comment by bruno-** [comment]
I'm doing issues cleanup.
I investigated this a bit and it seems currently there's no way to detect if clock is shown in the pane.

**Comment by soyuka** [comment]
Np not a big deal anyway :). Thanks for trying though!
