### ISSUE TITLE
Does not resurrect on a new machine.

### ISSUE THREAD

**Issue by absorber** [tmux-plugins/tmux-resurrect#77]
I moved my .tmux.conf and .tmux/ to a new machine, as well as my .bashrc, but still tmux-resurrect can not resurrect my session there.

[Here is the directory structure of .tmux/](https://gist.github.com/absorber/c87e2522a5b886c5dce3)

Here's my [.tmux/resurrec/last and my .tmux.conf](https://gist.github.com/absorber/4fac7968eecbe54f1f09)

**Comment by bruno-** [comment]
Hey,
can you please check what is the output of `$ cat ~/.tmux/resurrect/last`. It seems as if the "last" file has an unusual symlink..

![screen shot 2015-03-02 at 2 29 24 pm](https://cloud.githubusercontent.com/assets/1042682/6441491/b1fd9698-c0e8-11e4-8aed-7f70d7ef35f7.png)

**Comment by absorber** [comment]
I had to save and restore, so the old `~/.tmux/resurrect/last` is gone, but I think I have a hunch of where the problem comes from.

```
$ cat ~/.tmux/resurrect/last
pane    logstats        0       :stats  1       :*      0       :/home/tst      0       htop    :htop
pane    logstats        0       :stats  1       :*      1       :/home/tst      0       sudo    :sudo iotop -o
pane    logstats        0       :stats  1       :*      2       :/home/tst      1       ping    :ping www.google.com -s 16
pane    logstats        0       :stats  1       :*      3       :/home/tst      0       watch   :watch -n1 free -m; df -h
pane    logstats        1       :logs   0       :-      0       :/home/tst      0       tail    :tail -F /var/log/syslog
pane    logstats        1       :logs   0       :-      1       :/home/tst      1       tail    :tail -F /var/log/kern.log
pane    logstats        2       :bash   0       :       0       :/home/tst      1       bash    :
pane    logstats        3       :bash   0       :       0       :/media/cd      1       bash    :
window  logstats        0       1       :*      9d6b,193x48,0,0[193x12,0,0,0,193x35,0,13{96x35,0,13[96x11,0,13,7,96x23,0,25,10],96x35,97,13,9}]
window  logstats        1       0       :-      168f,193x48,0,0[193x24,0,0,6,193x23,0,25,11]
window  logstats        2       0       :       6752,193x48,0,0,13
window  logstats        3       0       :       6753,193x48,0,0,14
state   logstats        logstats
```

This is from the remote machine. On the local machine I have a different user (with a different username: ab). So perhaps this is why it didn't resurrect?

**Comment by absorber** [comment]
I can confirm that when transferring `~/.tmux/resurrect/last` on a new machine which has a different user than where the session was previously saved as, that it's no longer resurrecting the session.

Perhaps change `/home/user` entries in `~/.tmux/resurrect/last` into `$HOME` instead?

**Comment by bruno-** [comment]
Hey,
I'd recommend manually updating the `~/.tmux/resurrect/last` in this scenario. Just open the `last` file and change all `/home/user` to `/home/newuser` and things should work fine.

**Comment by 22459** [comment]
Could there be some kind of warning if someone attempts to run resurrect under a different user, since it's expected to break?
