### ISSUE TITLE
Is it possible to restore from particular log file?

### ISSUE THREAD

**Issue by blelump** [tmux-plugins/tmux-resurrect#78]
Hi!

I've accidentally put `^B + S` instead of `^B + R` (restore) so that Resurrect persisted my shiny blank session and cannot restore the old one. I've tried to put some earlier version name of *.log file to `last`, but nothing happen. Is it possible to restore session from any *.log file?

**Comment by bruno-** [comment]
Hi,
yes, it should definitely be possible to restore from an earlier log file!

Here are the steps:

- `$ cd ~/.tmux/resurrect/`
- locate the save file you'd like to use for restore (file names have a timestamp)
- symlink the `last` file to the desired save file: `$ ln -sf <file_name> last`
- do a restore with `tmux-resurrect` key: `prefix + Ctrl-r`

I hope you'll have no trouble to make this work so I'm going to close this issue. Feel free to reopen if you have more questions though.

**Comment by blelump** [comment]
Indeed, you're right :-) . Sorry for bothering you. I was playing with exact same scenario but it seems that with incorrect .log file (the one already broken).
