### ISSUE TITLE
vim and nvim dont want to reopen file

### ISSUE THREAD

**Issue by stephanedemotte** [tmux-plugins/tmux-resurrect#84]
Hi !

Thanks for your great plugin,

I have some issue with it, when i open some files with vim or neovim, only the one in the first window re-open correctly, with the other one, vim open but any files are loaded.

I run obsession on  VimEnter

Any idea ?

Thanks !!

**Comment by bruno-** [comment]
Hey,
can you please provide the following:

- contents of `~/.tmux/resurrect/last` file
- contents of `.tmux.conf`

I suppose you have these lines in your `.tmux.conf`?

    set -g @resurrect-strategy-vim 'session'
    set -g @resurrect-strategy-nvim 'session'

Also if you manually go to the directory where you open vim/neovim and then do `vim -S`, what happens?

**Comment by bruno-** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this.

**Comment by yevhen-m** [comment]
I have the same issues -- tmux-resurrect does not restore my vim sessions.
```
tmux 2.2
nvim 0.1.6-dev
zsh 5.0.2
ubuntu 14.04
```
When I do `vim -S` vim starts and loads my session as expected.

![image](https://cloud.githubusercontent.com/assets/10185058/19206757/dd707812-8cf3-11e6-8eea-56b83f33b758.png)

`.tmux.conf` part
```

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'nhdaly/tmux-scroll-copy-mode'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```
