### ISSUE TITLE
Using Alt instead of Ctrl

### ISSUE THREAD

**Issue by santosh79** [tmux-plugins/tmux-resurrect#85]
Hi Bruno,
Thank you for your using plugin. I am having trouble using the Alt key instead of the control. Ctrl-J Ctrl-S works great (I have my tmux prefix mapped to J instead of A) but Ctrl-J Alt-S doesn't.

Any help is much appreciated.

Thank you.

**Comment by bruno-** [comment]
I think putting this in `.tmux.conf` should do the trick:

    set -g @resurrect-save 'M-s'

I'll close the issue, but feel free to reopen or comment if this is not working an I'll try to help
