### ISSUE TITLE
Sessions.vim file path

### ISSUE THREAD

**Issue by zaferot** [tmux-plugins/tmux-resurrect#87]
Hi,
`tmux-resurrect` searches for `Sessions.vim` in the current directory. However, `vim-obsession` allows to define an arbitrary directory for the `Sessions.vim` file.  In such a case `tmux-resurrect` will not restore Vim session even though `Sessions.vim` file exists.

For example, I have `$HOME/.vim/session` directory to keep `Sessions.vim` file. It would be great if `tmux-resurrect` could check this directory too.

Is it possible to add a new option for such directory? (e.g.` set -g @resurrect-session-dir '/some/path'`)

**Comment by bruno-** [comment]
Hey @zaferot,
thanks for getting involved.

The vim session restore "strategy" implementation is here: https://github.com/tmux-plugins/tmux-resurrect/blob/master/strategies/vim_session.sh
Strategies are decoupled from the rest of the code, so you can basically look only at that file and it's relatively simple.

How about writing another strategy that would restore vim sessions in this other way?

**Comment by zaferot** [comment]
Thanks for the fast reply!

Actually, I've already adopted the `vim_session.sh` to my use case. It is working fine for me. However, I use `Tmux Plugin Manager` for managing Tmux plugins. Thus, I would like to be in sync with master.
So, I've come to you to find some general purpose solution for this case.  If it's possible.

My idea is to add an option to define some arbitrary directory for the `Sessions.vim` file. As someone may want to keep the session files somewhere else (not only in `$HOME/.vim/session. It's like the `@resurrect-dir` option defines a directory to save Tmux environment .

**Comment by zaferot** [comment]
Hi,
Let's close this case as I've started using [Vim-CtrlSpace](https://github.com/szw/vim-ctrlspace) plugin and it plays well with original `tmux-resurrect`.

Thanks!

**Comment by lvarayut** [comment]
@zaferot Could you explain how did you solve it?

**Comment by zaferot** [comment]
Hi @lvarayut. I use [Vim-CtrlSpace](https://github.com/szw/vim-ctrlspace) plugin which is also can manage Vim sessions. This plugin can automatically save and restore the previous Vim session.
I need just start Vim and my last sessions is automatically restored. Actually, `tmux-resurrect` just spawns `vim` command in appropriate `tmux` pane. That's all. Check out [Vim-CtrlSpace](https://github.com/szw/vim-ctrlspace) docs.

**Comment by lvarayut** [comment]
Thanks @zaferot, I'll check it out!
