### ISSUE TITLE
restoring a specific tmux session not the latest

### ISSUE THREAD

**Issue by cshintov** [tmux-plugins/tmux-resurrect#89]
Hi, 
Thanks for tmux-resurrect..
I wanted to know whether is it possible to restore an earlier **specific** session stored in .tmux/resurrect directory instead of the latest session saved.
Thank you.

**Comment by bruno-** [comment]
Hi,
yes, that should be possible. Can you please check second tip from the top [here](https://github.com/tmux-plugins/tmux-continuum#faq) and let me know if that helps?

**Comment by cshintov** [comment]
Hi.. That worked.. Thanks for the fast reply :)

**Comment by bruno-** [comment]
Cool, glad it helped.

**Comment by eyalev** [comment]
That's the referenced text if anyone's looking:

> I want to make a restore to a previous point in time, but it seems that save is now overwritten?

None of the previous saves are deleted (unless you explicitly do that). All save files are kept in ~/.tmux/resurrect/ directory.
Here are the steps to restore to a previous point in time:

* make sure you start this with a "fresh" tmux instance
* $ cd ~/.tmux/resurrect/
* locate the save file you'd like to use for restore (file names have a timestamp)0
* symlink the last file to the desired save file: $ ln -sf <file_name> last
* do a restore with tmux-resurrect key: prefix + Ctrl-r
