### ISSUE TITLE
restoring tmux to new computer

### ISSUE THREAD

**Issue by 2marshall8** [tmux-plugins/tmux-resurrect#92]
If I want to move all my tmux ressurect panes to another computer do I simply get tmux installed and than copy over all the bash_history and ressurect files from the ~/.tmux/resurrect folder on the original PC into the same folder on the new PC?

**Comment by bruno-** [comment]
Hey,
I never tried this, but I think that should do the trick.

A couple things to keep in mind:

- Make sure all the pane directories exist. If you try restoring panes and their path does not exist on a new computer, the pane won't be restored.
- Please make sure you're using the same user name on both machines. Example: if you're using user `foo` on an old machine, pane directories relative to your home dir will be saved as something like `/home/foo/some_dir`. If you use user `bar` on a new machine dir `/home/foo/some_dir` likely won't exist.

Hope that helped and let us know if it works.
